### ISSUE TITLE
Calling settings words inconsistent

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-embeddable#109]
![image](https://user-images.githubusercontent.com/733544/40468840-2481b5cc-5f61-11e8-8711-c8c3450aae8b.png)

![image](https://user-images.githubusercontent.com/733544/40469145-23bb4d1e-5f62-11e8-82b0-7e61c890b6af.png)

I think we should change "My Location" to "My RingCentral Phone", just to be consistent.

**Comment by embbnux** [comment]
The calling setting is updated. `My RingCentral Phone` is renamed into RingOut
![image](https://user-images.githubusercontent.com/7036536/93452780-699bdc00-f90b-11ea-9ac0-35b9a1429260.png)
