### ISSUE TITLE
SalesForce integration: is it possible to retrieve the details about the clicked phone number's Object (i.e. Opportunity) from the Widget?

### ISSUE THREAD

**Issue by dcrck** [ringcentral/ringcentral-embeddable#112]
Title has the question. I tried accessing the URL, but the focus changes to the Widget and the URL is different. I'm trying to log the call directly to the object that the number is attached to (i.e. Opportunity) Wondering if there are any workarounds for the scenario I'm trying to enable. Thanks.

**Comment by embbnux** [comment]
Hi, @rederekt Now the Widget doesn't support to retrieve the Object data. 

But I think you can flag the phone number with the Object in salesforce onClickToDial event `opencti.onClickToDial` in VisualForce page scripts. And when you get call log event from the widget, use phone number from the call info and the flag to retrieve Object.

Following show how to use salesfore ClickToDial with the Widget.
