### ISSUE TITLE
Company associated with RC account is not found

### ISSUE THREAD

**Issue by andrewklaus** [ringcentral/ringcentral-embeddable#176]
I'm getting this error message.
![image](https://user-images.githubusercontent.com/9679972/50023379-f3719380-0019-11e9-9ec5-e38c9a776f4b.png)
Which is called or run periodically when the APP is running.
Already set all information of Company at https://service.devtest.ringcentral.com but still issue persist.
Though all I want if possible is to remove GLIP if possible or remove that call if it will not cause any issue.

**Comment by embbnux** [comment]
Hi, @andrewklaus This is a bug of glip sandbox API. Our engineer is working on this. [The Glip feature](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/disable-features.md#enable-glip-feature) is disabled by default. And it is enabled in our live demo https://ringcentral.github.io/ringcentral-embeddable/ If you embed this widget to your website, it is disabled by default

**Comment by tance77** [comment]
Status on this? This still seems to be happening 8 months later.

**Comment by embbnux** [comment]
Hi @tance77, the root cause is that Glip feature didn't enable by default. User need to use my glip app before using Glip api. For sandbox user: https://glip.devtest.ringcentral.com, production user: https://app.glip.com/
