### ISSUE TITLE
Allow apps to add desired User Agent into X-USER-AGENT header

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable#199]

**Comment by grokify** [comment]
Allow apps to pass in User Agent string to be passed into JS SDK `X-User-Agent` header as seen here.

Ideally: 

1. the app using Embeddable should pass in its desired `X-User-Agent` string to Embeddable.
1. Embeddable should concatenate the app-supplied string with it's own string with version number, e.g. "RingCentral Embeddable v0.2.1" and pass the combined string the RingCentral JS SDK.
1. the RingCentral JS SDK should take the app supplied string from Embeddable and concatenate it with it's own string

JS SDK Setting the User Agent Header:

https://github.com/ringcentral/ringcentral-js/blob/631349cdbaa28e7454e51d6660e41c28f6a43cfc/src/platform/Platform.js#L510

JS SDK Generating the User Agent Header with its own `RCJSSDK` string.

https://github.com/ringcentral/ringcentral-js/blob/631349cdbaa28e7454e51d6660e41c28f6a43cfc/src/platform/Platform.js#L68-L70

**Comment by embbnux** [comment]
@grokify In PR #200 , it allow user to pass userAgent into widget to add user agent string into X-User-Agent header. Do you think `userAgent` is good name?
