### ISSUE TITLE
Missing sessionId in event payload for call placed through browser

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#202]
Calls initiated via the embeddable, but performed over an actual cell phone (i.e. RingOut calls) have event payloads that contain a `sessionId`. e.g. the payload below received for the `rc-ringout-call-notify` type event:

```
{
    "call": {
      "to": {
        "phoneNumber": "+18881234567"
      },
      "from": {
        "phoneNumber": "+18007005555"
      },
      "missed": false,
      "offset": -2346,
      "endTime": 1550594203307,
      "partyId": "cs17527610337041089187-1",
      "sipData": {
        "toTag": "gK048e43bb",
        "fromTag": "10.114.128.71-5070-3764231c56be4",
        "localUri": "do-not-use-me-I-am-useless",
        "remoteUri": "do-not-use-me-I-am-useless"
      },
      "direction": "Outbound",
      "sessionId": "197986214031",
      "startTime": 1550594162141,
      "telephonyStatus": "NoCall",
      "terminationType": "final",
      "telephonySessionId": "Y3MxNzUyNzYxMDMzNzA0MTA4OTE4N0AxMC4xMTQuMTI4Ljcx"
    },
    "type": "rc-ringout-call-notify"
  }
```

BUT, a call placed via the browser (i.e. through the embeddable), the payload received for the event does not contain the `sessionId` value. e.g:
```
{
    "call": {
      "id": "c4pri0qhi3q6h47frra8o3m51npcp8",
      "to": "+18007005555",
      "from": "14567891230*102",
      "cached": false,
      "callId": "c4pri0qhi3q6h47frra8",
      "endTime": 1550005897035,
      "removed": false,
      "isOnFlip": false,
      "isOnHold": false,
      "isOnMute": false,
      "direction": "Outbound",
      "isReplied": false,
      "minimized": false,
      "partyData": {
        "partyId": "cs169612397976113760-1",
        "sessionId": "Y3MxNjk2MTIzOTc5NzYxMTM3NjBAMTAuMjguMjAuMTA5"
      },
      "startTime": 1550005877910,
      "callStatus": "webphone-session-connected",
      "fromNumber": "+13234021966",
      "isForwarded": false,
      "creationTime": 1550005862077,
      "isOnTransfer": false,
      "recordStatus": "webphone-record-idle",
      "isToVoicemail": false,
      "lastActiveTime": 1550005862077
    },
    "type": "rc-call-end-notify"
  }
```

Note that `partyData.sessionId` in payload 2 is not equivalent to `sessionId` in payload 1.

**Comment by embbnux** [comment]
Hi @ElridgeDMello , you are right. Now the web phone call doesn't have session id. It is caused by this issue https://github.com/ringcentral/ringcentral-web-phone/issues/132. We will fix this after our SIP server support this.  

You can listen to `Active Call Event` which includes web phone call and ringout call, and it includes session id https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#active-call-event

**Comment by ElridgeDMello** [comment]
Thanks @embbnux for that info - I think that will get us what we need.

**Comment by embbnux** [comment]
You are welcome. For mapping from web phone session and active call, you can use `partyData.sessionId` and `telephonySessionId`.
