### ISSUE TITLE
Programatically set 'from' number

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#230]
Hello,

Is there a way to programmatically set the 'from' number before a call is made?

![image](https://user-images.githubusercontent.com/1136153/57251959-b336a000-7010-11e9-9c42-183c6a09013f.png)

We would like to specify the best number based on area code when dialing out.

**Comment by ElridgeDMello** [comment]
Relatedly, is there a way to get the list of From numbers via the widget?

**Comment by embbnux** [comment]
@ElridgeDMello Now the widget haven't provided that data and API. Will talk to PM about this.

**Comment by embbnux** [comment]
Hi, @ElridgeDMello We released a new version in our [master](https://ringcentral.github.io/ringcentral-embeddable/#) build. Now it support to get from numbers and set from number by API. You can try it with this [document](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/interact-with-calling-settings.md#enable-call-from-number-setting)

**Comment by ElridgeDMello** [comment]
Hi @embbnux thanks for the update, this is promising.  

I just checked this out and have some feedback before this could be useable:

1. I do not see a `fromNumbers` key in the `rc-calling-settings-notify` event data that is logged:
```{type: "rc-calling-settings-notify", callWith: "browser", callingMode: "webphone"}``` 


2. Firing the `rc-calling-settings-notify` _only_ when the call settings are changed, would lead to a problematic user interaction.  If the only way we can programmatically get the list of the fromNumbers is when the user changes this setting, it would not be possible for us to get the list _unless and until_ the user sets their `callWith` to `browser`.  e.g. if they have set this in the past.
Alternatively, in the case that their `callWith` has previously been set to `browser`, could this event fire on widget load?

**Comment by embbnux** [comment]
Hi @ElridgeDMello, do you add `enableFromNumberSetting` in URI. The widget will only show fromNumbers in `rc-calling-settings-notify` when it is enabled and callWith is "browser". 

And `rc-calling-settings-notify` is fired when page loaded or setting changed. So you can get it when page is loaded without setting changed.

**Comment by ElridgeDMello** [comment]
Sorry, I missed that step.  I had tried it out on the [demo page](https://ringcentral.github.io/ringcentral-embeddable/).  Will try it out.  Thanks!

**Comment by embbnux** [comment]
Cool! Look forward to your feedback, Thanks

**Comment by ElridgeDMello** [comment]
Hi @embbnux, I tried out loading the widget with the `enableFromNumberSetting` in URI.  

It fires the `rc-calling-settings-notify` event on widget load (great!) and settings change, but the data does not include the `fromNumbers` list. 

Here's the data that is logged in the browser console:
`rc-calling-settings-notify: {type: "rc-calling-settings-notify", callWith: "browser", callingMode: "webphone"}`

Full url used to load the widget:
https://apps.ringcentral.com/integration/ringcentral-embeddable/1.0.0/adapter.js?enableFromNumberSetting=1&appKey=myAppKey&appSecret=myAppSecret=https://platform.devtest.ringcentral.com

**Comment by embbnux** [comment]
Hi @ElridgeDMello Sorry for miss this message. `FromNumberSetting` is supported on master release. And will supported in 1.0.1.  And your full url is 1.0.0. 
I will update in here when 1.0.1 released.

**Comment by embbnux** [comment]
1.0.1 released

**Comment by ElridgeDMello** [comment]
Hi @embbnux, thanks for that!  This is working for us now.  Thanks much for the follow up!

**Comment by embbnux** [comment]
That's awesome that it works for you.
