### ISSUE TITLE
Get access token without customizing the redirect uri

### ISSUE THREAD

**Issue by amz27** [ringcentral/ringcentral-embeddable#235]
I wanted to create an interface for users to access the call recordings.
[https://developers.ringcentral.com/guide/call-log/manual/recordings](url)
By following the above guideline, I need the access token to fetch the list of Call Logs.
Is there any way we can get the access token using the default redirect uri ([https://ringcentral.github.io/ringcentral-embeddable/redirect.html](url))?

**Comment by embbnux** [comment]
Hi @amz27, this issue is same as #233 
We will support to pass call recording uri (can be downloaded) to your app.

**Comment by embbnux** [comment]
Hi @amz27 , We have added recording with token support in our master build. You can follow this docs to try it. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/third-party-service-in-widget.md#add-call-logger-button-in-calls-page

**Comment by embbnux** [comment]
@amz27 Hi, I think you are trying the new recording token api in other issue. Do you still need to get token as you mentioned?
Or I am going to close this issue?

**Comment by amz27** [comment]
@embbnux Thanks for the help. I got what I want, the API is really helpful.

**Comment by embbnux** [comment]
Cool. Thanks @amz27, I will close this issue.
