### ISSUE TITLE
Call logger message event

### ISSUE THREAD

**Issue by amz27** [ringcentral/ringcentral-embeddable#245]
After I registered the call logger service and enabled the Auto log calls in settings, I found that the message event would not only be fired when a call is finished, but also after "init call" (when user creates a call) and "start call" states (when an incoming call is accepted or an outbound call is connected).

**Comment by embbnux** [comment]
Yeah, you are right. I think this is mistake in docs. Some developers want to create log when call started. And update call log when call status is updated.

**Comment by embbnux** [comment]
closed by inactive
