### ISSUE TITLE
Need a way to see sms history

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-embeddable#254]
> Hey Drake Zhao Thanks! This is about the Click to SMS functionality in the Hubspot integration.. Actually it is a feedback from a customer that I spoke with a couple of days ago..

> So when you are in the contacts tab, and Click to SMS a number in your contacts, The RC Widget appears and populates the phone number that you want to send the SMS to which is normal behavior. However, You cannot see the message thread/history not until you have sent an SMS to that number. (If you go in the messages tab in the RC widget and go to the SMS, the thread/history shows there but not when you initiate the Click to SMS in the contacts tab).

> Anyway chance that this can be improved though?

From James Lao#ringcentral

**Comment by embbnux** [comment]
I am thinking to add a param in SMS API:
```js
document.querySelector("#rc-widget-adapter-frame").contentWindow.postMessage({
  type: 'rc-adapter-new-sms',
  phoneNumber: `phone number`,
  text: `your text`,
  conversation: true,
}, '*');
```
When conversation is true, it will go to conversation page directly when there is conversation with this phone number.
