### ISSUE TITLE
After adding new call, please provide a button and function to swap between calls

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-embeddable#28]
Story: 

1. Make a inbound/outbound call
2. With Add call button , make a new call
3. Create a new button called swap - keep this inactive if there is only one call
4. When there are >1 calls swap button should be active
5. Swap click should swap between calls ( i am not sure how to swap if there are >2 call sessions)

**Comment by embbnux** [comment]
Hi, @vyshakhbabji .  When user have multiple call, user can go to Active Calls Page to get all call list and switch call. When user click green button of a hold call, it will switch to this call and hold previous call
![41509599240_ pic](https://user-images.githubusercontent.com/7036536/32310654-e9b0f390-bfce-11e7-8754-f8207b8d7e3a.jpg)
![51509599289_ pic](https://user-images.githubusercontent.com/7036536/32310655-eeadb27a-bfce-11e7-95e6-7ef0bc76cda0.jpg)

**Comment by vyshakhbabji** [comment]
I am assuming we need sessions telephony api endpoint to swap between the active calls. I will keep a tab on this functionality and get back to you

**Comment by embbnux** [comment]
Yes, Sessions telephony API will be very useful for this

**Comment by embbnux** [comment]
Supported. Now we support to swap call from active call in other device into current web phone call.
