### ISSUE TITLE
Cloned Project, Doesn't Work

### ISSUE THREAD

**Issue by ashleycorinnex** [ringcentral/ringcentral-embeddable#284]
My embeddable project worked great yesterday but now I upgraded my node modules (npm i) and now it is broken. Just to make sure it wasn't on my end I cloned the embeddable project directly and tried running it and it still does not work. I keep getting this error: "Uncaught TypeError: Cannot read property 'getUIProps' of undefined" in node_modules/ringcentral-widgets/lib/phoneContext/index.js?54d2. Could you help my team and I out? 

![Capture](https://user-images.githubusercontent.com/46426941/63893666-a19e4d00-c99f-11e9-9487-b6ec5ad135d6.PNG)

UPDATE! My team found that if we added these lines to your base project in src/modules/phone/index.js it works again:

```
import AlertUI from 'ringcentral-widgets/modules/AlertUI';
import ConnectivityBadgeUI from 'ringcentral-widgets/modules/ConnectivityBadgeUI';

 { provide:'ConnectivityBadgeUI', useClass:ConnectivityBadgeUI },
 { provide:'AlertUI', useClass:AlertUI },
```

**Comment by embbnux** [comment]
Hi @ashleycorinnex It is caused by upgrading in `ringcentral-widgets` lib. We have updated Embeddable codes to use new version of widgets lib https://github.com/ringcentral/ringcentral-embeddable/pull/283 .

It is recommended to use `yarn`,  it will install dependences based on `yarn.lock`. so you can keep dependences locked unless you upgrade them manually.

**Comment by ashleycorinnex** [comment]
> Hi @ashleycorinnex It is caused by upgrading in `ringcentral-widgets` lib. We have updated Embeddable codes to use new version of widgets lib #283 .
> 
> It is recommended to use `yarn`, it will install dependences based on `yarn.lock`. so you can keep dependences locked unless you upgrade them manually.

Thank you!
