### ISSUE TITLE
It is unsafe to expose Client Id and Client Secret in a browser based app

### ISSUE THREAD

**Issue by mangatinanda** [ringcentral/ringcentral-embeddable#285]
[It is critical that developers never include their client_secret in public (mobile or browser-based) apps](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)

Anyone can steal them and misuse it. 

There should be an alternate way to refresh the session like an event that must be fired before the session expires. It is the host application problem to securely refresh the access token to extend the session.

**Comment by embbnux** [comment]
Yes, you are right. Now we also provide implicit auth flow that only need app client id in client side. But login session will be expired if user is not active in a hour. 
And we also have some investigation on server-side auth proxy which will handle authorization in server-side.

**Comment by mangatinanda** [comment]
Awesome. Thanks for the prompt reply.

The way I envision it, the embeddable should take the url as input. When clicked on login button, a window opens the url, which should redirect to Ringcentral login page, and when the oAuth is successful, the window will send the auth data to the embeddable. 

For all the subsequent refresh token requests, the embeddable should fire a postMessage event. The enclosing application should perform the refresh token request and send back the refreshed auth data to the embeddable. Let me know if this approach makes sense. I will try to come up with a PR.

**Comment by embbnux** [comment]
That's great idea. I think we can also just fire a postMessage when user click login button. So web that outside the widget will handle auth flow.
Now we can pass token to the widget by following message api:

New token:
```
widgetIframe.contentWindow.postMessage({
   callbackUri: 'your_redirect_uri?access_token=...&expires_in=...&endpoint_id=...&token_type=...'
}, *)
```
Refresh token:
```
widgetIframe.contentWindow.postMessage({
   refreshCallbackUri: 'your_redirect_uri?access_token=...&expires_in=...&endpoint_id=...&token_type=...'
}, *)
```

**Comment by embbnux** [comment]
Will update the app to use authorization code with PKCE flow. So client secret is not needed in client side.  Need to wait https://github.com/ringcentral/ringcentral-js-widgets support PKCE.

PKCE introduction article:
https://medium.com/ringcentral-developers/use-authorization-code-pkce-for-ringcentral-api-in-client-app-e9108f04b5f0

**Comment by embbnux** [comment]
The widget has supported authorization code with PKCE. So client secret is not required now.
