### ISSUE TITLE
Dialer search drop-down goes in front of the dial buttons 

### ISSUE THREAD

**Issue by ashleycorinnex** [ringcentral/ringcentral-embeddable#287]
When I click the dialer buttons the search drop-down drops in front of the buttons so I am not able to click anymore unless I close the drop-down each time.

![image](https://user-images.githubusercontent.com/46426941/64802435-8145c500-d53f-11e9-9f7b-be827ddceb3d.png)

**Comment by embbnux** [comment]
Thanks @ashleycorinnex, it is auto-complete feature in dialer input. Will feedback to PM for better user experience
