### ISSUE TITLE
Contact Details Not Showing All Properties

### ISSUE THREAD

**Issue by ashleycorinnex** [ringcentral/ringcentral-embeddable#288]
The Embeddable contact details page is missing contact properties such as Job Title and Company. It would also be great if we could add our own meta data properties because we want to add Manager and Username from our own database.

![image](https://user-images.githubusercontent.com/46426941/64874024-1a87e080-d5ff-11e9-957d-0f01aaf7ef2f.png)

**Comment by embbnux** [comment]
Thanks @ashleycorinnex It is great idea. Will talk with our PM about this.

**Comment by embbnux** [comment]
@ashleycorinnex we have supported to show company and job title in contact detail page in v1.0.3
