### ISSUE TITLE
Press Enter twice to dial from dialer

### ISSUE THREAD

**Issue by curtishollawayTSI** [ringcentral/ringcentral-embeddable#290]
Would it be possible for users that type phone numbers to call to be able to call that number after pressing enter twice?  Our experience with Skype (Lync) works this way and feels intuitive.

**Comment by embbnux** [comment]
Hi @curtishollawayTSI , it is great idea. Will investigate if we can do that in web page.

**Comment by curtishollawayTSI** [comment]
We have taken over the dialer functionality.  This is no longer an issue for us.
