### ISSUE TITLE
Contact Thumbnail does not appear in the list until after navigating to details

### ISSUE THREAD

**Issue by curtishollawayTSI** [ringcentral/ringcentral-embeddable#291]
We have put our contact Thumbnail photos on extensions and they are not showing on the contacts page until we drill into their details.  From that point on they are available in the list.

Would like to see the photo available in the list.

**Comment by embbnux** [comment]
Hi @curtishollawayTSI, it is by design now. We disabled to load avatars in list page for performance issue. Will feedback to team and find a way to resolve it

**Comment by curtishollawayTSI** [comment]
We have taken over the contact list completely with our own directory.  This is no longer an issue.
