### ISSUE TITLE
Custom Contact Search on Transfer Panel

### ISSUE THREAD

**Issue by curtishollawayTSI** [ringcentral/ringcentral-embeddable#292]
We would like to be able to inject our own contact search functionality when the transfer page is loaded.

Our use case is:
To avoid a queue, someone calls in and asks to speak with the person they are trying to get in touch with.  On the transfer panel, if this person is part of a queue, we want to hide their direct extension and only allow the queue to be chosen.  In the normal Dialer, we would like the extension to be available as a target, just not in the transfer scenario.

**Comment by embbnux** [comment]
Thanks @curtishollawayTSI It is a great idea, will feedback to our PM

**Comment by curtishollawayTSI** [comment]
Since the target list on a transfer is very specific to each company, we've decided to take this on ourselves.  Closing the issue.
