### ISSUE TITLE
Default app client id will be removed in versioned Embeddable

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable#298]
Default app client id will be removed in versioned Embeddable (1.0.2 [CDN version](https://github.com/ringcentral/ringcentral-embeddable/releases)). So it is required to create your own RingCentral app client id and pass to Embeddable widget, [this](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md) is docs to setup your own RingCentral app.

**Comment by SampsonCrowley** [comment]
Ok, how does that work for newcomers that just want a drop in embed? not everyone knows how to force the embeddable to hit every API 5 times to make it to production

**Comment by SampsonCrowley** [comment]
I thought the whole point of this was so that we have a drop-in website embed for users that don't have the capability to develop something themselves

**Comment by embbnux** [comment]
@SampsonCrowley Good point.  Will think more about this. For example, provide docs for how to make app production. 
We still provide default client id in master build https://ringcentral.github.io/ringcentral-embeddable/adapter.js . 
Thanks so much.

**Comment by SampsonCrowley** [comment]
@embbnux Looks good
