### ISSUE TITLE
Unable to test embeddable using developer sandbox account

### ISSUE THREAD

**Issue by JiandongRuan** [ringcentral/ringcentral-embeddable#302]
I am hitting similar #97 issue. But I was unable to create the "RingCentral for Desktop" device without getting a new number, which isn't free. Is there anyway to test embeddable in sandbox for free?

**Comment by embbnux** [comment]
Hi @JiandongRuan Before you use our desktop app in sandbox, you need to add a device and assign to your extension in here http://service.devtest.ringcentral.com/ 

 https://developers.ringcentral.com/guide/basics/your-rc-phone

![image](https://user-images.githubusercontent.com/7036536/68108831-edcbb780-ff23-11e9-939e-2bf29acd1b51.png)

**Comment by JiandongRuan** [comment]
Today, I went through exactly the same steps which I did when I opened this issue. This time, getting the free new number completed successfully.
