### ISSUE TITLE
Feature request.  Allow secondary speaker for ringing

### ISSUE THREAD

**Issue by curtishollawayTSI** [ringcentral/ringcentral-embeddable#303]
On Skype (Lync for business) we could set a secondary speaker for ringing.  It allows the users to use a headset, but when it is set down to still hear the phone ring.  Is this possible?

**Comment by embbnux** [comment]
Thanks @curtishollawayTSI Will investigate if web app can support this.

**Comment by embbnux** [comment]
We can set audio speaker with `setSinkId` API https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId . And this API only is supported in Chrome, and limited in Firefox. 
But can't make two speakers play on same Audio element. So maybe we can try with two Audio element to play same ringing.

**Comment by curtishollawayTSI** [comment]
@embbnux Thank you for doing the look up.  Our use case is building and distributing an electron app which utilizes chromium so we don't have to worry about additional browser scenarios.  I validated that I can set up an audio stream and attach it to a different speaker.  Is this something you will be buiding pretty soon on this project or should we come up with our own solution for short term?  I think we will be looking to utilize this feature in about 1 month.

**Comment by embbnux** [comment]
@curtishollawayTSI  I think you should come up with your own solution for short term.  We don't have plan for this recently. 
I think you can try to hack audio helper in web phone `phone.webphone._webphone.userAgent.audioHelper`. We call this to play incoming ringing: `phone.webphone._webphone.userAgent.audioHelper.playIncoming(1)`. You can find source code in here https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/audioHelper.ts

**Comment by curtishollawayTSI** [comment]
We have implemented our own solution based on Embbnux feedback.  Closing issue.
