### ISSUE TITLE
Unexpected rc-active-call-notify events telephonyStatus state transitions

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#321]
When we make a call, the `rc-active-call-notify` events received (in sequence) occasionally go through the following `telephonyStatus` state transitions  (even though the call gets connected to the target number):

* Unexpected sequence:
Ringing -> NoCall -> Ringing -> CallConnected -> NoCall

* However, the expected sequence of state transitions is (most times this happens):
Ringing -> CallConnected -> NoCall

Is there a reason for the transitions to go from Ringing -> **_NoCall -> Ringing ->_** CallConnected -> NoCall, or is this a bug?

We're using embeddable version 1.0.3.

I have a HAR file and console log that I can email to devsupport with regard to this if further info is needed for you to troubleshoot.  Please advise.

**Comment by embbnux** [comment]
Hi @ElridgeDMello Can you send HAR file to rc devsupport(devsupport@ringcentral.com), so we can track the issue. It should be a bug.

**Comment by ElridgeDMello** [comment]
@embbnux I just emailed file links to devsupport.

**Comment by embbnux** [comment]
Thanks @ElridgeDMello Got the email

**Comment by embbnux** [comment]
hi @ElridgeDMello , can you try on 1.1.0. we have some enhancement to fix active call notify issue.

**Comment by ElridgeDMello** [comment]
@embbnux thanks for the fix pushed out.  I tried a few calls with this version and didn't experience the issue.  However, for what it's worth, when the issue did occur previously, it occurred only sporadically.  Will report if we notice this issue again.

**Comment by embbnux** [comment]
thanks @ElridgeDMello

**Comment by embbnux** [comment]
Will close this issue for inactive. Feel free to reopen it if you get this issue again.
