### ISSUE TITLE
Voice Message: ability to seek

### ISSUE THREAD

**Issue by curtishollawayTSI** [ringcentral/ringcentral-embeddable#330]
Feature request.  Can we get the ability to seek to a different point in a voice message while we are listening to it?

**Comment by embbnux** [comment]
Hi @curtishollawayTSI, we can do this. Will discuss with PM team to add it into backlog.

**Comment by embbnux** [comment]
Hi @curtishollawayTSI  Feedback from team, as team are focusing on other features, we don't plan about this recently. Will keep you updated here.

**Comment by embbnux** [comment]
Supported with 2.x version https://ringcentral.github.io/ringcentral-embeddable/docs/2.x/
