### ISSUE TITLE
Is there any way forward call from postMessage ?

### ISSUE THREAD

**Issue by mzahirr** [ringcentral/ringcentral-embeddable#334]
Hi I can answer call from postMessage like ; 
document.querySelector("#rc-widget-adapter-frame").contentWindow.postMessage({
                    type: 'rc-adapter-control-call',
                    callAction: 'answer',
                }, '*');

But I need to forward call from postMessage . Can you please help ?

**Comment by embbnux** [comment]
Hi @mzahirr , we haven't support this. It is good point. We will talk with our PM and add this api soon. Thanks

**Comment by embbnux** [comment]
hi @mzahirr @AbdullahYavuzyigitoglu, just release a new version on [master build](https://ringcentral.github.io/ringcentral-embeddable/) which supports to forward call. You can follow the [docs](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#forward-a-ringing-call) to try it. 
**Notice**: It hasn't been in stable CDN release now.

**Comment by mzahirr** [comment]
Hi @embbnux thanks for interest . It is working now.  Can you please add 'mute' and 'unmute' events ?

**Comment by embbnux** [comment]
@mzahirr Sure

**Comment by embbnux** [comment]
The `forward` api is released in 1.1.1
