### ISSUE TITLE
Could not decode a text frame as UTF-8

### ISSUE THREAD

**Issue by mzahirr** [ringcentral/ringcentral-embeddable#335]
I get this error "WebSocket connection to 'wss://sip111-wss.devtest.ringcentral.com:8083/' failed: Could not decode a text frame as UTF-8."

![Screenshot from 2020-01-14 15-11-39](https://user-images.githubusercontent.com/5872984/72343556-35b74980-36e0-11ea-99e1-1f74bacf9ece.png)

**Comment by embbnux** [comment]
Thanks for feedback @mzahirr. It seems a bug in some condition.  Can you reproduce this always, or some time. Can you send your browser information (version, language) here?

**Comment by embbnux** [comment]
Hi @mzahirr , just want to check if there are some chars that not english in your RingCentral account name. We have a known parse issue when the name is like French or Russian.

**Comment by mzahirr** [comment]
Hi @embbnux yes it is special character issue. Expample 'ö' .
