### ISSUE TITLE
Contact view tab

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable#34]
It would be nice to see all the contact in a tab. I see that a request gets made to get all of the contacts but no where do I see where you can view them all. You can only do a lookup via text messaging

**Comment by AndyHaas** [comment]
Or an Idea, is there a way to get the data that the widget is getting and use the data somewhere else on the page?

**Comment by embbnux** [comment]
Yes, you are right. We will add contacts tab in web widget when contacts feature is finished in [Widgets](https://github.com/ringcentral/ringcentral-js-widgets) library . And It also will provide a API to receive contacts from page or other platforms

**Comment by embbnux** [comment]
- [ ] add contacts list tab
- [ ] API to import third party contacts

**Comment by embbnux** [comment]
add contacts list by (#42)

**Comment by AndyHaas** [comment]
Can you add the Contact Link on the Main page instead of going to the More menu?

**Comment by AndyHaas** [comment]
Are we also able to take the data that the web app is subscribing to and use it?

**Comment by embbnux** [comment]
Yeah, it is better to add the contact tag to main page. I will update it.
And for taking the data that the web app is subscribing, It is what we will do in next.

**Comment by embbnux** [comment]
Move contacts tab to main (#45)

**Comment by embbnux** [comment]
Hi, @AndyHaas  Now the widget support to import third party contacts by API. https://github.com/ringcentral/ringcentral-embeddable-voice/blob/master/docs/third-party-service-in-widget.md Free feel to give any suggestions in here.
