### ISSUE TITLE
Can't release web phone registration on Firefox 72 Ubuntu. 

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable#343]
Reported in here https://github.com/ringcentral/ringcentral-embeddable/pull/271. Will trigger 5 web phone limitation when refreshing page sometimes

**Comment by embbnux** [comment]
Reproduced in Firefox 72 MacOS

**Comment by embbnux** [comment]
The root cause is that app can not sent unregister message (by WebSocket) successfully in window unload event in Firefox.

**Comment by embbnux** [comment]
Link same issue https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/182

**Comment by vini-brito** [comment]
Just to add that in Ubuntu, Firefox 80.0.1 (64-bits) I get the same issue.

**Comment by embbnux** [comment]
fixed in https://github.com/ringcentral/ringcentral-embeddable/pull/476 After getting 5 web phone limitation error, app will create a new endpoint id to reconnect.
