### ISSUE TITLE
How Can I use logged in users phone number and extention number ? 

### ISSUE THREAD

**Issue by mzahirr** [ringcentral/ringcentral-embeddable#347]
![image](https://user-images.githubusercontent.com/5872984/73739585-907c1800-4757-11ea-9337-fa631d96f17a.png)

Hi , I'm trying to get phone number and extention number logged in user . But  I can't get phone number and extention number ? How can I get ?

**Comment by embbnux** [comment]
@mzahirr we just released the [feature](https://github.com/ringcentral/ringcentral-embeddable/pull/346) into master build, not in CDN build.
You can try with https://ringcentral.github.io/ringcentral-embeddable/adapter.js

**Comment by mzahirr** [comment]
Actually we have pull master branch in my development environment. I'm trying build my master branch . For example 'yarn build' and I have try login with ringcentral but I can't see any log .

**Comment by embbnux** [comment]
@mzahirr Are you using the latest code? You can try to start the app in local with `yarn start`, and try in `localhost:8080`.

**Comment by mzahirr** [comment]
Solved. Thanks

**Comment by mzahirr** [comment]
Solved. Thanks
