### ISSUE TITLE
RingCentral Web Widget integrated with Plantronics

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable#35]
Just adding this here original thread was on RingCentral Dev Portal
https://devcommunity.ringcentral.com/ringcentraldev/topics/ringcentral-web-widget-integrated-with-plantronics

I am using https://github.com/ringcentral/ringcentral-web-widget and I am looking to see if I can integrate the Plantronics headset into the application. 

Currently we have the Windows Desktop Softphone installed and that currently has controls integrated into it to control the Plantronics base unit. 

I am looking do do these things

When an inbound call comes in, I want the headset to beep in the clients ear to let them know a call is coming

When you click the button on the headset to pickup/hangup the call to actually pickup or hang up the call

Some type of volume control that is separate from the windows sound.

Thank You
Andy Haas﻿

**Comment by embbnux** [comment]
As commented in devcommutity, we need to add following API to web widget
- [ ] audio device selection
- [ ] end the call
- [ ] answer the call

**Comment by AndyHaas** [comment]
I see the audio device selection on the settings tab, just an inquiry; will this work with the plantronics hardware?
![rc_dial_audio](https://user-images.githubusercontent.com/22582720/33030450-f2f2f460-cde0-11e7-9781-50666d5c0b65.JPG)

**Comment by embbnux** [comment]
Hi, @AndyHaas Now the widget support to select device. And we provide API to ctrl the call out of iframe. But I don't know how to get the button event from headset. I will investigate it

**Comment by stephanatjabra** [comment]
Hi, i wonder if the APIs have been created. i did see a desktop application providing call control and assume that RingCentral released API's an application can call on? I cannot find anything on the RingCentral developer site... thx!

**Comment by embbnux** [comment]
Hi @stephanatjabra Do you mean https://github.com/ringcentral/ringcentral-embeddable-electron-app, it is a Embeddable app with electron

**Comment by embbnux** [comment]
close by inactive. Feel free to reopen it
