### ISSUE TITLE
İs Call internal(from extension) or external?

### ISSUE THREAD

**Issue by abdullahyyo** [ringcentral/ringcentral-embeddable#353]
Hi everyone again;
We need identify call is internal or external call on embeddable project. We recognized callInfo doesn't have any column for this situation. We are using from number with some validations for this case but we think there is a better and exact way.

Is there any call attribute to identify call is internal(from extension) or external?

Thanks

**Comment by embbnux** [comment]
Hi @abdullahyyo , now we only can check it by phone number length. For length that less or equal 6 is call from internal extension.

**Comment by embbnux** [comment]
closed by inactive. Feel free to reopen
