### ISSUE TITLE
Add pop-out and pop-in functionality

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-embeddable#354]
Support ability to do pop-out and pop-in.

Will there be any issues with communicating with the webpage in pop-out mode?

# Pop-out

<img width="275" alt="pop-out" src="https://user-images.githubusercontent.com/209872/75204682-63070680-5726-11ea-8025-6d7637014e43.png">

# Pop-in

<img width="292" alt="pop-in" src="https://user-images.githubusercontent.com/209872/75204694-6ac6ab00-5726-11ea-9bfe-b9743cb2db72.png">

**Comment by embbnux** [comment]
@grokify The issue of pop-out mode is that only the current tab that open the popup window can communicate with with it. If user close the tab page, the popup window will be out of control.

**Comment by embbnux** [comment]
supported at master build.
