### ISSUE TITLE
How can I learn who the person calling me has closed the call and the other side has closed call?

### ISSUE THREAD

**Issue by mzahirr** [ringcentral/ringcentral-embeddable#355]
![image](https://user-images.githubusercontent.com/5872984/75860784-72b0da00-5e0d-11ea-986b-595d6ab90ee9.png)
Hi , How can I learn who the person calling me has closed the call and the other side has closed call?

For example : call_status : 'abandoned'

**Comment by embbnux** [comment]
Hi @mzahirr In web phone notification, we don't `abandoned` status.
You can check `startTime` if undefined, it should a missed call. Or you need to track the `callStatus`. If there are `connected` status, it should be a `answered` call.

**Comment by embbnux** [comment]
closed by inactive

**Comment by mzahirr** [comment]
Hi @embbnux , this is important for me . The main problem here is that the call was interrupted during the call. We cannot find out what this is caused by. for example, the call ends at the 20th second of the call. We want to know if the other party has closed it. So we can detect the problem. Can you help us with this?

**Comment by embbnux** [comment]
Hi @mzahirr For detail call information, now you can use TelephonySession API to query it. https://developers.ringcentral.com/api-reference/Call-Control/readCallSessionStatus It will show detail parties data

**Comment by mzahirr** [comment]
Hi @embbnux , thank for advice. I'm trying to get call logs for session id .  
Is sessionId telephonySessionId? i'm querying this id but i get 404 error.

![image](https://user-images.githubusercontent.com/5872984/89280416-45cd5100-d651-11ea-807d-149f5b2b7dfa.png)

**Comment by embbnux** [comment]
> Hi @embbnux , thank for advice. I'm trying to get call logs for session id .
> Is sessionId telephonySessionId? i'm querying this id but i get 404 error.
> 
> ![image](https://user-images.githubusercontent.com/5872984/89280416-45cd5100-d651-11ea-807d-149f5b2b7dfa.png)

It is telephonySessionId. For call ended very long or dropped, telephonySession will be deleted https://developers.ringcentral.com/api-reference/Call-Control/deleteCallSession

**Comment by mzahirr** [comment]
@embbnux My purpose is not to learn the status of the call currently. I want to know who closed the call in the past calls.

**Comment by embbnux** [comment]
> @embbnux My purpose is not to learn the status of the call currently. I want to know who closed the call in the past calls.

Got it. I think we can use call log data https://developers.ringcentral.com/api-reference/Call-Log/readUserCallRecord
![image](https://user-images.githubusercontent.com/7036536/89282689-7a0b3680-d67e-11ea-9d0a-9db616e995b8.png) 

You can request by yourself.  Or in widget app, when user log call, it will send detail call log to third party  https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/third-party-service-in-widget.md#log-call-into-your-service

**Comment by mzahirr** [comment]
@embbnux  How can we find callRecordId ? 
![image](https://user-images.githubusercontent.com/5872984/89283300-98107100-d655-11ea-98a5-30c274d8b778.png)

**Comment by embbnux** [comment]
It is call log id. You can use call log list api and query with sessionId if you don't get call log id  https://developers.ringcentral.com/api-reference/Call-Log/readUserCallLog

**Comment by mzahirr** [comment]
@embbnux yes i use exactly that.
 I have tried this recordId but getting error -> "Resource for parameter [callRecordId] is not found"


![Screenshot from 2020-08-04 13-34-58](https://user-images.githubusercontent.com/5872984/89284452-7b753880-d657-11ea-90f1-5f165ead6970.png)

**Comment by mzahirr** [comment]
Yes, I have now fulfilled this request. However, there is still no information about who ended the call.

`{
  "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/extension/62497647008/call-log/IhwJ2_ySaFlBzUA?view=Detailed",
  "id": "IhwJ2_ySaFlBzUA",
  "sessionId": "412358860008",
  "startTime": "2020-08-03T13:45:21.025Z",
  "duration": 12,
  "type": "Voice",
  "direction": "Inbound",
  "action": "Phone Call",
  "result": "Accepted",
  "to": {
    "name": "Nicholas Casale",
    "phoneNumber": "+17403420523",
    "extensionId": "62497647008"
  },
  "from": {
    "name": "AMERICAN FREIGH",
    "phoneNumber": "+17403632222",
    "location": "Delaware, OH"
  },
  "recording": {
    "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/recording/1325626979008",
    "id": "1325626979008",
    "type": "Automatic",
    "contentUri": "https://media.ringcentral.com/restapi/v1.0/account/3241273008/recording/1325626979008/content"
  },
  "extension": {
    "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/extension/62497647008",
    "id": 62497647008
  },
  "reason": "Accepted",
  "reasonDescription": "The call connected to and was accepted by this number.",
  "telephonySessionId": "s-cc7e0369a4954a74856b7a3080cc46da",
  "transport": "PSTN",
  "lastModifiedTime": "2020-08-03T13:45:52.065Z",
  "billing": {
    "costIncluded": 0,
    "costPurchased": 0
  },
  "legs": [
    {
      "startTime": "2020-08-03T13:45:21.025Z",
      "duration": 12,
      "type": "Voice",
      "direction": "Inbound",
      "action": "Phone Call",
      "result": "Accepted",
      "to": {
        "name": "Nicholas Casale",
        "phoneNumber": "+17403420523",
        "extensionId": "62497647008"
      },
      "from": {
        "name": "AMERICAN FREIGH",
        "phoneNumber": "+17403632222",
        "location": "Delaware, OH"
      },
      "extension": {
        "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/extension/62497647008",
        "id": 62497647008
      },
      "reason": "Accepted",
      "reasonDescription": "The call connected to and was accepted by this number.",
      "telephonySessionId": "s-cc7e0369a4954a74856b7a3080cc46da",
      "transport": "PSTN",
      "legType": "Accept",
      "master": true
    },
    {
      "startTime": "2020-08-03T13:45:22.538Z",
      "duration": 10,
      "type": "Voice",
      "direction": "Outbound",
      "action": "VoIP Call",
      "result": "Call connected",
      "to": {
        "phoneNumber": "+19738594000",
        "extensionNumber": "39304",
        "location": "Passaic, NJ"
      },
      "from": {
        "name": "Nicholas Casale",
        "phoneNumber": "+17403632222",
        "extensionId": "62497647008",
        "device": {
          "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/device/802878607008",
          "id": "802878607008"
        }
      },
      "recording": {
        "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/recording/1325626979008",
        "id": "1325626979008",
        "type": "Automatic",
        "contentUri": "https://media.ringcentral.com/restapi/v1.0/account/3241273008/recording/1325626979008/content"
      },
      "extension": {
        "uri": "https://platform.ringcentral.com/restapi/v1.0/account/3241273008/extension/62497647008",
        "id": 62497647008
      },
      "reason": "Accepted",
      "reasonDescription": "The call connected to and was accepted by this number.",
      "telephonySessionId": "s-cc7e0369a4954a74856b7a3080cc46da",
      "transport": "VoIP",
      "legType": "PstnToSip"
    }
  ]
}`

**Comment by embbnux** [comment]
You can get reason field in call log.  You can find detail description here https://developers.ringcentral.com/api-reference/Call-Log/readUserCallLog
![image](https://user-images.githubusercontent.com/7036536/89285275-a4f78980-d682-11ea-8f99-26c26c6125eb.png)

**Comment by mzahirr** [comment]
@embbnux yes  i know this area but only "reason": "Accepted"
 I see it as.

**Comment by mzahirr** [comment]
isn't the log added here when the call ends like in this picture?

![Screenshot from 2020-08-04 13-42-40](https://user-images.githubusercontent.com/5872984/89290396-7a490900-d661-11ea-899a-50521b964aee.png)

**Comment by embbnux** [comment]
> @embbnux yes i know this area but only "reason": "Accepted"
> I see it as.

Hi @mzahirr , can you help to send email to `devsupport@ringcentral.com` to show your requirements in cal log API about this.

**Comment by embbnux** [comment]
> isn't the log added here when the call ends like in this picture?
> 
> ![Screenshot from 2020-08-04 13-42-40](https://user-images.githubusercontent.com/5872984/89290396-7a490900-d661-11ea-899a-50521b964aee.png)

Not sure about this. I think the picture just shows call log data. Can you help to send email to support email, so our engineers can find if Service Web can show the detail call result.

**Comment by embbnux** [comment]
closed by inactive
