### ISSUE TITLE
No event fired when outbound call is answered

### ISSUE THREAD

**Issue by mstf55** [ringcentral/ringcentral-embeddable#358]
rc-call-start-notify' is fired when outbound call is started but i need an event to be fired when outbound call is answered. It is this event already exist? We want to know whether a call is answered from outbound side. How can i do that? Thanks in advance.

**Comment by embbnux** [comment]
Hi @mstf55 , for calls between RingCentral account, `rc-call-start-notify` is triggered when callee's device connected (ringing).  When you make call to a physical phone, `rc-call-start-notify`  is triggered when call is answered.

**Comment by embbnux** [comment]
closed by inactive.
