### ISSUE TITLE
Warm transfer feature request

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#359]
This is a feature request:  

Can you please add warm transfer as a feature on your roadmap, if not already on there?  This is functionality that exists in the Ringcentral Desktop app and apparently supported in the [ringcentral-web-phone](https://github.com/ringcentral/ringcentral-web-phone#warm-transfer).  

Ability for the user to perform a warm transfer in the UI, but it would be a bonus to also have programmatic support for this feature (could be phased in later).

Thanks!

**Comment by embbnux** [comment]
Thanks @ElridgeDMello added it into our roadmap

**Comment by Brutalbeard** [comment]
@embbnux for this one, any timelines available? I think there was an issue with APIs not existing for it.

**Comment by embbnux** [comment]
> @embbnux for this one, any timelines available? I think there was an issue with APIs not existing for it.

We can do this by web phone SIP API.
I am working on this feature in widgets lib from this week. After release in widgets, we can add it into Embeddable. In should be done at end of Feb or early of Mar.

**Comment by Brutalbeard** [comment]
Thanks for the heads up!

**Comment by embbnux** [comment]
Supported in master build now

**Comment by embbnux** [comment]
supported at 1.6.0

**Comment by kpandey017** [comment]
@embbnux can you share some example for this feature

**Comment by embbnux** [comment]
Hi @kpandey017 For warm transfer, we call it "Ask first". It allow user to have a call with person who the user want to transfer to ask first.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/7036536/178218331-f14a16a1-a219-4c77-b55f-f3e43fd3b4e2.png">
You can get more details here https://www.ringcentral.com/call-transfers.html

**Comment by kpandey017** [comment]
Hi @embbnux does it have programmatic support for this feature (postMessage API.).

**Comment by embbnux** [comment]
@kpandey017 It don't have API for warm transfer now, Cold transfer is supported. 
Do you need this? Can you provide some details about why you need this. I can talk with our PM to add this.
