### ISSUE TITLE
Support to send SMS without clicking on Send button using clickToSMS

### ISSUE THREAD

**Issue by bakhshandeh** [ringcentral/ringcentral-embeddable#361]
I want to send SMS using clickToSMS directly without clicking on Send button.
Can you add a new parameter to clickToSMS and let the users submit the SMS form automatically?
Something like RCAdapter.clickToCall(phoneNumber, true)

**Comment by embbnux** [comment]
Hi @bakhshandeh It is by design now. As SMS can't be canceled as Call. So we don't support to send it directly now.
I will talk with PM about this if we can improve it. Thanks for good point!

**Comment by embbnux** [comment]
Closed by inactive
