### ISSUE TITLE
rcvideo/bridges permissions error awareness

### ISSUE THREAD

**Issue by JoshKing87** [ringcentral/ringcentral-embeddable#370]
Recently our App error rates of skyrocketed by almost 600,000 errors, and we are seeing the error connecting to GET: rcvideo/bridges.  We have noticed that this is due to our app not having pre-existing permissions set to read 'Meetings.'

Here is one days worth of errrors:
![image](https://user-images.githubusercontent.com/26283574/79392004-6e590000-7f27-11ea-8c5a-aac59e115fa9.png)

Switching to an older/pre-versioned copy of the JS fixes the issue. However we want to let you know that this is an issue that you should allow users to configure somewhere to prevent further errors in their apps.

**Comment by embbnux** [comment]
Thanks so much @JoshKing87 , will fix it soon to check permission before request.
