### ISSUE TITLE
Company associated with RC account is not found

### ISSUE THREAD

**Issue by imshreya** [ringcentral/ringcentral-embeddable#373]
Hi I am getting 400 status code on createcalenderevent apis. with following error message "Company associated with RC account is not found" and I am also unable to login to https://glip-app.devtest.ringcentral.com/.

**Comment by embbnux** [comment]
hi @imshreya Can you send email to devsupport@ringcentral.com with detail sandbox account info. It seems there are issues in new sandbox account with glip, and not related to this project.
