### ISSUE TITLE
1 Second live talk log appears on analytics.ringcentral.com when I used to callAction: 'forward'

### ISSUE THREAD

**Issue by mzahirr** [ringcentral/ringcentral-embeddable#389]
Hi , I tried to 1 example call scenario. I called one number and I didn't answer. If the call is not answered within 10 seconds, I will forward it to the next number. But when I examine the life cycle of the call at https://analytics.ringcentral.com/, a 1 second live talk appears. What is the reason of this ? 
Please check attachment.
![Screenshot from 2020-06-10 13-46-32](https://user-images.githubusercontent.com/5872984/84266020-7b136200-ab2c-11ea-8251-364a5867a713.png)

**Comment by embbnux** [comment]
Hi @mzahirr , for `Forward` feature in web phone (Browser mode), it works as following steps:
* Accept incoming call with muted mode
* Transfer call

So you can get a 1 second call when forward call.

You can get full code of `Forward call` here https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/session.ts#L689

**Comment by embbnux** [comment]
Close by inactive. Feel free to reopen
