### ISSUE TITLE
How to stop/pause and release the recording in embedded app, once the automatic call recording is enabled in the ring central admin portal

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#390]
How to stop/pause and release the recording in embedded app, once the automatic call recording is enabled in the ring central admin portal. Please help.

**Comment by embbnux** [comment]
Hi @KailashvasanVK We don't support it in web phone mode now. Will check with team to confirm if we can support it.

**Comment by embbnux** [comment]
Create a issue in web phone sdk https://github.com/ringcentral/ringcentral-web-phone/issues/292

**Comment by embbnux** [comment]
As we talked in email, user can't handle recording in Embeddable widget when auto recording is enabled in `service.ringcentral.com`.
So we need to disable auto recording setting. And can implement auto recording in Embeddable by following code:

```js
window.addEventListener('message', (e) => {
  const data = e.data;
  if (data) {
    switch (data.type) {
      case 'rc-call-start-notify':
        // get call when a incoming call is accepted or a outbound call is connected
        console.log(data.call);
        document.querySelector("#rc-widget-adapter-frame").contentWindow.postMessage({
          type: 'rc-adapter-control-call',
          callAction: 'startRecord',
          callId: data.call.id
        }, '*');
        break;
      default:
        break;
    }
  }
});
```
And docs: 
https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#web-phone-call-event 
https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#record-a-call

**Comment by tylerlong** [comment]
I know this is an old issue and closed.

But as I tested, WebPhone SDK 2.0 supports it out-of-box. 
I don't know why 1.x and 0.8.x don't support it.
