### ISSUE TITLE
How to do customization on the Embedded app. 

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#392]
How to do customization on the Embedded app? We want to add some rich textbox to get some inputs from the user and do some api calls on call button events. 

We got to make some these changes in the Libraries as well (Under node_modules) and using it in production. Will it get affected from any future version changes of the Ring central embedded updates.

**Comment by embbnux** [comment]
Hi @KailashvasanVK It is not recommended to update code under `node_modules `. It will be removed if dependencies updated.
For now, you can listen `rc-call-init-notify` event when user start a call, https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#web-phone-call-event
And make your UI hover on Embeddable's UI?

**Comment by KailashvasanVK** [comment]
> Hi @KailashvasanVK It is not recommended to update code under `node_modules `. It will be removed if dependencies updated.
> For now, you can listen `rc-call-init-notify` event when user start a call, https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#web-phone-call-event
> And make your UI hover on Embeddable's UI?
Hi. We have made the code to point to our reporsitory (For Node_Modules changes) instead of embedded github repository. Could you please help on understanding the UI customization changes on the screen, like adding HTML controls to the existing screen render.

**Comment by embbnux** [comment]
Hi @KailashvasanVK Can you share details what you want to add in Embeddable. So We can find good solution for it. If you are not good to share public, feel free to send email to `devsupport@ringcentral.com`.

This project is based on React and Redux, and [RingCentral Widgets](https://github.com/ringcentral/ringcentral-js-widgets). For customizing logics and UI, we can create modules (state manager) or containers/components(UI) in this project to instead from RingCentral widgets.

But it will be better, if we can create standalone app to interact with RingCentral Embeddable based on message API. So you can just focus on your logics and UI, and have your own framework.  We are still have active development on message API, so we can create new API if we need in your app.

**Comment by KailashvasanVK** [comment]
> Hi @KailashvasanVK Can you share details what you want to add in Embeddable. So We can find good solution for it. If you are not good to share public, feel free to send email to `devsupport@ringcentral.com`.
> 
> This project is based on React and Redux, and [RingCentral Widgets](https://github.com/ringcentral/ringcentral-js-widgets). For customizing logics and UI, we can create modules (state manager) or containers/components(UI) in this project to instead from RingCentral widgets.
> 
> But it will be better, if we can create standalone app to interact with RingCentral Embeddable based on message API. So you can just focus on your logics and UI, and have your own framework. We are still have active development on message API, so we can create new API if we need in your app.

**Hi we are displaying CallID in the UI. We have a textarea in UI where we put the ClaimID's in it and saved to DB when we disconnect the call. For this we have changed the node_modules files to accomodate the UI changes and made the app to point to our node_modules folder instead of github. Can you please share your contact number to discuss on this on a short call? Request you help on this customization such that there is no impact in the future for us. 

Also when we start a call, the CallID/SessionID is not coming for the 1st call alone in the event "rc-active-call-notity" inorder to display it in the UI. But for next subsequent calls, it is coming. Could you please help clarify on the same.**

**Comment by embbnux** [comment]
> > Hi @KailashvasanVK Can you share details what you want to add in Embeddable. So We can find good solution for it. If you are not good to share public, feel free to send email to `devsupport@ringcentral.com`.
> > This project is based on React and Redux, and [RingCentral Widgets](https://github.com/ringcentral/ringcentral-js-widgets). For customizing logics and UI, we can create modules (state manager) or containers/components(UI) in this project to instead from RingCentral widgets.
> > But it will be better, if we can create standalone app to interact with RingCentral Embeddable based on message API. So you can just focus on your logics and UI, and have your own framework. We are still have active development on message API, so we can create new API if we need in your app.
> 
> **Hi we are displaying CallID in the UI. We have a textarea in UI where we put the ClaimID's in it and saved to DB when we disconnect the call. For this we have changed the node_modules files to accomodate the UI changes and made the app to point to our node_modules folder instead of github. Can you please share your contact number to discuss on this on a short call? Request you help on this customization such that there is no impact in the future for us.
> 
> Also when we start a call, the CallID/SessionID is not coming for the 1st call alone in the event "rc-active-call-notity" inorder to display it in the UI. But for next subsequent calls, it is coming. Could you please help clarify on the same.**

Sorry for miss this message.

Hi @KailashvasanVK I still recommend that you to build app based prebuilt files, not from source code. You can make your UI hover on this app, so keep your app standalone. And you can just focus on your business logics. For contact, can you send email to `devsupport@ringcentral.com`. It will create ticket automatically, and our developers can have a quick response.

**Comment by embbnux** [comment]
You can also create new `app.html` file as https://github.com/ringcentral/ringcentral-embeddable/blob/master/src/app.html and add your JS file to work with `https://ringcentral.github.io/ringcentral-embeddable/app.js` to get full scope.

**Comment by embbnux** [comment]
Resolved in email. A demo code to customize UI component from widgets lib: https://github.com/ringcentral/ringcentral-embeddable/commit/c07163d2df8ea374aefd559a9bf84edac281750e
