### ISSUE TITLE
Getting the error as "web phone unavailable" from the embedded widget application integrated into our app

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#397]
Getting the error as "web phone unavailable" from the embedded widget application integrated into our app from a pop up page. 

"web phone unavailable"
"Sorry, making calls using this browser is not supported"
"Please grant RingCentral Embeddable to access your audio."

But this is working when we access it seperated from a html page. only from our app pop up page hosted in a server throwing this error. Please help

**Comment by embbnux** [comment]
Hi @KailashvasanVK Want to check which protocol your website uses. This widget will require microphone permission from Browser for web phone. And Browser only allow https page for microphone.

**Comment by embbnux** [comment]
closed by inactive
