### ISSUE TITLE
Embedded widget app - window.phone.callHistory.calls - recordingID not getting updated intermittently for the records

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#398]
Embedded widget app- window.phone.callHistory.calls - recordingID not getting updated intermittently for the records inside it.
we are retrieving the recordingID from this object and storing in the DB against the callID.
Please help.

**Comment by embbnux** [comment]
Hi @KailashvasanVK It is by design. As server need time to generate recording file after call ended. Client side will get notification to refresh recording id and URI after recording generated
