### ISSUE TITLE
Lines are getting disconnected intermediately with errors

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#399]
Embedded widget app - Lines are getting disconnected intermediately stating session expired with the errors attached screenshot.
The call is getting disconnected while the users are on call for more than 30 minutes and then the below attached [errors](url) pop 
Dialer state is changing to offline intermediately. 
[Uploading RC App-Errors.docx…]()

Error:
Session expired. Please sign in
Cannot connect to the server. Please retry later

**Comment by embbnux** [comment]
Link original post with screenshot https://forums.developers.ringcentral.com/questions/10824/embedded-widget-app-lines-are-getting-disconnected.html

**Comment by embbnux** [comment]
@KailashvasanVK and which environment are you using, Sandbox or Production. If you set `appServer=https://platform.devtest.ringcentral.com`, it is sandbox environment?

**Comment by embbnux** [comment]
For tracking the issue, can you send HAR file (when the issue happened) to `devsupport@ringcentral.com`. So we can have deep investigation of it. There are some reasons that can trigger session expired.

**Comment by KailashvasanVK** [comment]
> @KailashvasanVK and which environment are you using, Sandbox or Production. If you set `appServer=https://platform.devtest.ringcentral.com`, it is sandbox environment?

We are using production only. (platform.ringcentral.com). We are getting various type errors given below. Could you please help on the cause for it
Errors:
1) Session expired. Please sign in
2) Cannot connect to the server. Please retry later
3) Ring Central dialer state changed to “Offline” intermediately 
4) If the login is Idle for 10-15 mins after call, the session is expired and it is logged off automatically.  I have to sign in again in order to make another call 
5) Call is getting disconnected intermediately (Say 2 out of 10 calls reported disconnected users reported)

**Comment by embbnux** [comment]
> > @KailashvasanVK and which environment are you using, Sandbox or Production. If you set `appServer=https://platform.devtest.ringcentral.com`, it is sandbox environment?
> 
> We are using production only. (platform.ringcentral.com). We are getting various type errors given below. Could you please help on the cause for it
> Errors:
> 
> 1. Session expired. Please sign in
> 2. Cannot connect to the server. Please retry later
> 3. Ring Central dialer state changed to “Offline” intermediately
> 4. If the login is Idle for 10-15 mins after call, the session is expired and it is logged off automatically.  I have to sign in again in order to make another call
> 5. Call is getting disconnected intermediately (Say 2 out of 10 calls reported disconnected users reported)

It is weird, can you open chrome developer tool, reproduce this issue. Then in network panel save all log as HAR file. And send HAR file to `devsupport@ringcentral.com` with app information.

**Comment by KailashvasanVK** [comment]
> > > @KailashvasanVK and which environment are you using, Sandbox or Production. If you set `appServer=https://platform.devtest.ringcentral.com`, it is sandbox environment?
> > 
> > 
> > We are using production only. (platform.ringcentral.com). We are getting various type errors given below. Could you please help on the cause for it
> > Errors:
> > 
> > 1. Session expired. Please sign in
> > 2. Cannot connect to the server. Please retry later
> > 3. Ring Central dialer state changed to “Offline” intermediately
> > 4. If the login is Idle for 10-15 mins after call, the session is expired and it is logged off automatically.  I have to sign in again in order to make another call
> > 5. Call is getting disconnected intermediately (Say 2 out of 10 calls reported disconnected users reported)
> 
> It is weird, can you open chrome developer tool, reproduce this issue. Then in network panel save all log as HAR file. And send HAR file to `devsupport@ringcentral.com` with app information.

Thanks. Yes sure will get and share the HAR file to that DL. But at high level these errors seems due to network connectivity related issues? In Implicit mode, if the browser is idle for 30 mins only, it will expire the session right? 
Also could you please advice on the which auth mode to select (auth code or Implicit) using the embedded widget app in our browser application

**Comment by embbnux** [comment]
Yes, it think the issue is most caused by poor network. But need to check with HAR file.

And for implicit grant flow, refresh token expires in 30 mins. So if user is not active in 30mins, it will fail to refresh token and logout.
For authorization code flow, refresh token expires in 7 days.  So user is not active in 7 days, it will fail to refresh token and logout.

It is recommended to use authorization code flow. But a concern is that need to keep app secret in client side. We are working on new auth flow `authorization code with PKCE` which will not require app secret in local with authorization code flow to resolve this concern.

**Comment by KailashvasanVK** [comment]
> Yes, it think the issue is most caused by poor network. But need to check with HAR file.
> 
> And for implicit grant flow, access token expires in 30 mins. So if user is not active in 30mins, it will fail to refresh token and logout.
> For authorization code flow, refresh token expires in 7 days. So user is not active in 7 days, it will fail to refresh token and logout.
> 
> It is recommended to use authorization code flow. But a concern is that need to keep app secret in client side. We are working on new auth flow `authorization code with PKCE` which will not require app secret in local with authorization code flow to resolve this concern.

Will it be possible to increase the token refresh timeout period? It is configured at the Ring central login API right

**Comment by embbnux** [comment]
Do you mean access token expired time?

In implicit flow, it is limited to 1 hour, but refresh session will be expired in 30 hour. So refresh timeout period is less 30 mins.

For authorization code flow, it is configurable. In our code, we use default 600s for access token. I think it is ok to use it, as app will auto refresh if access token expired.

**Comment by KailashvasanVK** [comment]
> > > > @KailashvasanVK and which environment are you using, Sandbox or Production. If you set `appServer=https://platform.devtest.ringcentral.com`, it is sandbox environment?
> > > 
> > > 
> > > We are using production only. (platform.ringcentral.com). We are getting various type errors given below. Could you please help on the cause for it
> > > Errors:
> > > 
> > > 1. Session expired. Please sign in
> > > 2. Cannot connect to the server. Please retry later
> > > 3. Ring Central dialer state changed to “Offline” intermediately
> > > 4. If the login is Idle for 10-15 mins after call, the session is expired and it is logged off automatically.  I have to sign in again in order to make another call
> > > 5. Call is getting disconnected intermediately (Say 2 out of 10 calls reported disconnected users reported)
> > 
> > 
> > It is weird, can you open chrome developer tool, reproduce this issue. Then in network panel save all log as HAR file. And send HAR file to `devsupport@ringcentral.com` with app information.
> 
> Thanks. Yes sure will get and share the HAR file to that DL. But at high level these errors seems due to network connectivity related issues? In Implicit mode, if the browser is idle for 30 mins only, it will expire the session right?
> Also could you please advice on the which auth mode to select (auth code or Implicit) using the embedded widget app in our browser application

Hi, Please find the HAR files Sent to the DL  `devsupport@ringcentral.com` with app information. Please help.
Please not that after refreshed the browser only we are able to get the attached HAR log.

**Comment by embbnux** [comment]
Thanks so much @KailashvasanVK 
>  Please not that after refreshed the browser only we are able to get the attached HAR log.
Do you mean you can't get full log after refreshed? You can enable `preserve log` to avoid clear log after refreshed

**Comment by KailashvasanVK** [comment]
> Thanks so much @KailashvasanVK
> 
> > Please not that after refreshed the browser only we are able to get the attached HAR log.
> 
> Do you mean you can't get full log after refreshed? You can enable `preserve log` to avoid clear log after refreshed

Thank you. Its intermittent, so we dont know which user would report this issue. We would enable this preserve log option for the users before they start working. So when they report the issue, we would open the developers tools from the browser and take our the HAR log. User need not keep the developer tools window open right when working, please confirm? only when they encounter the issue, we would open developer tools and take our HAR log, correct?

**Comment by embbnux** [comment]
> > Thanks so much @KailashvasanVK
> > > Please not that after refreshed the browser only we are able to get the attached HAR log.
> > 
> > 
> > Do you mean you can't get full log after refreshed? You can enable `preserve log` to avoid clear log after refreshed
> 
> Thank you. Its intermittent, so we dont know which user would report this issue. We would enable this preserve log option for the users before they start working. So when they report the issue, we would open the developers tools from the browser and take our the HAR log. User need not keep the developer tools window open right when working, please confirm? only when they encounter the issue, we would open developer tools and take our HAR log, correct?

Yes, user need not keep the developer tools window open right when they reproduce this issue.

**Comment by embbnux** [comment]
Closed, as mentioned in #404
