### ISSUE TITLE
Which auth flow is used in the Embedded widget app. 

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#400]
Which auth flow is used in the Embedded widget app? How to find that
From the Ring central developers site, could see both flows enabled for the app. But wanted to find out which one used in the code.

**Comment by embbnux** [comment]
Hi @KailashvasanVK If you didn't set app key and secret with this docs https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md , it will use authorization code by default.

**Comment by KailashvasanVK** [comment]
> Hi @KailashvasanVK If you didn't set app key and secret with this docs https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md , it will use authorization code by default.

Thanks for the reply. But the above link say, If we provide appsecret then it will use auth code flow by default. correct?
But wanted to know where we would give the appsecret in the code? is it the .env.default file is where we control this with appsecret entry. Please help

**Comment by embbnux** [comment]
> > Hi @KailashvasanVK If you didn't set app key and secret with this docs https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md , it will use authorization code by default.
> 
> Thanks for the reply. But the above link say, If we provide appsecret then it will use auth code flow by default. correct?
> But wanted to know where we would give the appsecret in the code? is it the .env.default file is where we control this with appsecret entry. Please help

yes, if you develop based on source code, app credentials are set in `.env` file. If you add appSecret in `.env` file, it will use authorization code flow.

**Comment by KailashvasanVK** [comment]
> > > Hi @KailashvasanVK If you didn't set app key and secret with this docs https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md , it will use authorization code by default.
> > 
> > 
> > Thanks for the reply. But the above link say, If we provide appsecret then it will use auth code flow by default. correct?
> > But wanted to know where we would give the appsecret in the code? is it the .env.default file is where we control this with appsecret entry. Please help
> 
> yes, if you develop based on source code, app credentials are set in `.env` file. If you add appSecret in `.env` file, it will use authorization code flow.

Thanks. So it does not use the below iframr script config for deciding the authorization mode? if used the code, then would use the env.default file only? Also could you please advice on which authorization mode do we select of those 2 (auth code or implicit). We are getting issues saying the session gets expired in the middle or call get cut disconnected in the middle.

<iframe width="300" height="500" id="rc-widget" allow="microphone" src="https://ringcentral.github.io/ringcentral-embeddable/app.html?appKey=your_app_client_id&appSecret=your_app_client_secret&appServer=https://platform.devtest.ringcentral.com">
</iframe>

**Comment by embbnux** [comment]
Yes, if use the code, it will use `.env` file (not env.default).  

For the expired issue, I think it is better to discuss in https://github.com/ringcentral/ringcentral-embeddable/issues/399 I add some questions in that.

**Comment by mstf55** [comment]
@embbnux we are having trouble with setting the .env file .Can you please provide with an example .env file? Which keys should be in .env file so we can get rid of that warning message on the console. Thanks in advance.

**Comment by embbnux** [comment]
Hi @mstf55 this is  example `.env` file. And what warning message do you get?

```
API_KEY=your_ringcentral_client_id
API_SERVER=https://platform.ringcentral.com
TEST_HOST_URI=http://localhost:8080
TEST_USER_NAME=
TEST_USER_PASSWORD=
TEST_HEADLESS=false
```

**Comment by mstf55** [comment]
"RingCentral client id is deprecated, it is required to setup your own RingCentral Client Id, Please stop using it soon before it is completely removed. Please follow here to setup your own RingCentral".
 Where do I need to set the clientId?
I tried 
https://myhost.com/adapter.js?clientId=myClientId&appServer=https://platform.ringcentral.com

But no luck , still getting the error.

**Comment by embbnux** [comment]
> "RingCentral client id is deprecated, it is required to setup your own RingCentral Client Id, Please stop using it soon before it is completely removed. Please follow here to setup your own RingCentral".
> Where do I need to set the clientId?
> I tried
> https://myhost.com/adapter.js?clientId=myClientId&appServer=https://platform.ringcentral.com
> 
> But no luck , still getting the error.

Hi @mstf55 , this is message that I added for developers who use precompiled build to recommend they to use [their own client id](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md)
If you are building from source code and `.env` file, you don't need to care about this warm message.

And it is also recommended to use our precompile build, and customize this app with provided APIs. If you don't have special requirements, you don't need to build it from source code.

**Comment by mstf55** [comment]
Thank you , appreciated

**Comment by anton-smyk** [comment]
Hi @embbnux, we also faced this warning.
Is that possible for you to remove this warning if the app is building from the source code and the `.env` file?
So other people in the future don't worry about it and don't search for this thread.

**Comment by embbnux** [comment]
Hi @anton-smyk sure. let me update code to only show the warning in the build in Github page and CDN. https://github.com/ringcentral/ringcentral-embeddable/issues/666

**Comment by anton-smyk** [comment]
> Hi @anton-smyk sure. let me update code to only show the warning in the build in Github page and CDN. #666

That will save some time for people in the future, appreciated.

**Comment by embbnux** [comment]
> > Hi @anton-smyk sure. let me update code to only show the warning in the build in Github page and CDN. #666
> 
> 
> 
> That will save some time for people in the future, appreciated.

Yes, thanks so much for the feedback

**Comment by anton-smyk** [comment]
Also @embbnux, it's not related, but I want to share the console log and ask you if there is something to worry about.
![image](https://user-images.githubusercontent.com/84497597/210337155-e9b55f76-f7e4-48e4-ab3f-e301334f2884.png)

Since we build it from the source and can change the code, we can get rid of that, but, as mentioned, people would prefer to see fewer warnings in the console :slightly_smiling_face:

**Comment by anton-smyk** [comment]
Btw, everything working as a clock, just wanted to share the feedback :slightly_smiling_face:

**Comment by embbnux** [comment]
> Also @embbnux, it's not related, but I want to share the console log and ask you if there is something to worry about. ![image](https://user-images.githubusercontent.com/84497597/210337155-e9b55f76-f7e4-48e4-ab3f-e301334f2884.png)
> 
> Since we build it from the source and can change the code, we can get rid of that, but, as mentioned, people would prefer to see fewer warnings in the console 🙂

For other warning, they are from our sub dependencies (widgets lib). It will not cause issues. And we will also need to upgrade it to avoid the warning.
