### ISSUE TITLE
Embedded widget app - Will it be possible to increase the token refresh timeout period for Implicit authorization type? 

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#401]
Embedded widget app - Will it be possible to increase the token refresh timeout period for Implicit authorization type? It is configured at the Ring central login API?

**Comment by embbnux** [comment]
A quote in https://github.com/ringcentral/ringcentral-embeddable/issues/399#issuecomment-650973706:

Do you mean access token expired time?

In implicit flow, it is limited to 1 hour, but refresh session will be expired in 30 hour. So refresh timeout period is less 30 mins.

For authorization code flow, it is configurable. In our code, we use default 600s for access token. I think it is ok to use it, as app will auto refresh if access token expired.

We can increase the token refresh timeout period, but need to find why need it?

**Comment by embbnux** [comment]
Closed, as @KailashvasanVK has changed to use auth code flow.
