### ISSUE TITLE
Auth code type authorization in embedded widget app, whether the token refreshes for every API calls?

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#402]
Auth code type authorization in embedded widget app, whether the token refreshes for every Ring central API calls?

I understand from the below link, that the session/token will be there for a period of 7 days. But wanted to clarify for RC API calls whether it refreshes token for every call. Please help clarify!

https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

In authorization code flow, if user is inactive in 7 days, user will be logged out. **The widget refreshes token when there are API requests to RingCentral API**. The refresh token will be expired in 7 days. So if user is active in 7 days, login session will be kept another 7 days. And when it refreshes token, app will get a new refresh token and old refresh token will be expired for security.

**Comment by embbnux** [comment]
Hi @KailashvasanVK , app does't refresh for every API calls. App save access token expired time in local. So before requesting API, it will check access token expired time. If token will be expired or has been expired, it will refresh token firstly, then request API.
You can find full logics in here https://github.com/ringcentral/ringcentral-js/blob/v3/src/platform/Platform.js
