### ISSUE TITLE
Embedded widget app - User getting "session expired" error when in middle of the call. 

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#403]
Embedded widget app - User getting "session expired" error when middle of the call. Intermittently happening for some users. Please help

![image](https://user-images.githubusercontent.com/40710114/86044054-2d24b680-ba67-11ea-9fdb-3041dcc0c136.png)

Error:
Session Expired. Please sign in again

**Comment by embbnux** [comment]
Close by same as https://github.com/ringcentral/ringcentral-embeddable/issues/399 , feel free to reopen it is new issue
