### ISSUE TITLE
Close by same as https://github.com/ringcentral/ringcentral-embeddable/issues/399 , feel free to reopen it is new issue

### ISSUE THREAD

**Issue by KailashvasanVK** [ringcentral/ringcentral-embeddable#404]
Close by same as https://github.com/ringcentral/ringcentral-embeddable/issues/399 , feel free to reopen it is new issue

_Originally posted by @embbnux in https://github.com/ringcentral/ringcentral-embeddable/issues/403#issuecomment-651599116_

When i disconnected the internet and checked the ring central app, this session expired error not coming. So need to investigate more whether its related to network issue. Please help on this error

**Comment by embbnux** [comment]
As we talked in email, it is recommended to use authorization code flow. Authorization code flow is more stable than implicit grant flow in poor network.
