### ISSUE TITLE
Can I disable SMS/Text but Keep Voicemail and Fax?

### ISSUE THREAD

**Issue by awood0540** [ringcentral/ringcentral-embeddable#407]
Can I disable SMS/Text but Keep Voicemail and Fax? If so, how? If not, can we add the functionality please?

**Comment by embbnux** [comment]
Hi @awood0540 It isn't supported now. Now it will only disable items when user don't have required permissions.
It is a good point to allow developers to disable it.

**Comment by embbnux** [comment]
Hi @awood0540 It is supported in master build. Can you help to try it?

**Comment by embbnux** [comment]
close by inactive. Feel free to reopen.
