### ISSUE TITLE
maximum of 5 soft phones could be registered - user can't login

### ISSUE THREAD

**Issue by vini-brito** [ringcentral/ringcentral-embeddable#446]
I often receive this error and can't properly login trough the widget.
Is there a workaround on this? A way to "unregister" a soft phone. Or possibly a fix.

**Comment by embbnux** [comment]
Hi @vini-brito, Do you mean that you can login but web phone connection fail in this widget?

You can logout to unregister web phone connections in current browser. 
And can you check if you enable multiple tabs support for this widget https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/multiple-tabs.md If you don't enable multiple tabs support, you can only open max 5 tabs with this widget.
And currently, we have issues in Firefox to unregister web phone connection when users refresh or close tab https://github.com/ringcentral/ringcentral-embeddable/issues/343
Another notice is the 5 soft phones limitation is for all RingCentral phone devices including RingCentral widget app, browser extension app and RingCentral desktop app.

**Comment by vini-brito** [comment]
So the user must always click logout instead of just closing the tab or browser?

**Comment by embbnux** [comment]
> So the user must always click logout instead of just closing the tab or browser?

If user got web phone limitation by having more than 5 widget tabs, user can just close tabs to avoid this error.

If when user got 5 web phone limitation error by some errors (such as Firefox issue), user need to logout to unregister web phone connections that losing control.

**Comment by vini-brito** [comment]
> If when user got 5 web phone limitation error by some errors (such as Firefox issue), user need to logout to unregister web phone connections that losing control.

This is the case. So one logout will unregister all soft phones? And it happens on Chrome too, but I haven't pinpointed a way to reproduce it yet. I just reload the page several times, one tab always, and after a couple hours it starts giving this error.
Then I reload the page several times and it starts working again.

**Comment by embbnux** [comment]
> > If when user got 5 web phone limitation error by some errors (such as Firefox issue), user need to logout to unregister web phone connections that losing control.
> 
> This is the case. So one logout will unregister all soft phones? And it happens on Chrome too, but I haven't pinpointed a way to reproduce it yet. I just reload the page several times, one tab always, and after a couple hours it starts giving this error.
> Then I reload the page several times and it starts working again.

The logout will only clean web phone connection in current app.

The widget sends web phone connection unregister request when it gets page unload event from Browser. But sometimes the unregister request will be not sent successfully, Browser will cancel the request. It happens always in Firefox, and occasionally in Chrome.

And do you enable multiple tabs supports for this widget https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/multiple-tabs.md . With this solution, it will reduce probability of getting web phone connection limitation error.

**Comment by embbnux** [comment]
fixed in #476 After getting 5 web phone limitation error, app will create a new endpoint id to reconnect.
