### ISSUE TITLE
bug: fax view/download button do not work

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-embeddable#449]

**Comment by embbnux** [comment]
A issue caused by chrome. after widget open a download link, user need to refresh the page to trigger download

**Comment by embbnux** [comment]
Okay, we can fix it by add `contentDisposition=Attachment` in download link

**Comment by embbnux** [comment]
voicemail download fixed in master build. Fax will be fixed after fixed in widgets lib

**Comment by embbnux** [comment]
fixed
