### ISSUE TITLE
error using github hosted embeddable

### ISSUE THREAD

**Issue by sarora2073** [ringcentral/ringcentral-embeddable#450]
Hi,

Am not sure if this is a critical error or not, as the embeddable appears to load, but I see the following error in the console:

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://ringcentral.github.io') does not match the recipient window's origin ('https://localhost:3000').

If i inspect the code that triggers this error i see this:

```
{
    key: "_postMessage",
    value: function _postMessage(data) {
      if (this._contentFrameEl.contentWindow) {
        this._contentFrameEl.contentWindow.postMessage(data, this._appOrigin);
      }
    }
  },
```

Context: 
I'm using the script provided in the [static CRM demo](https://ringcentral-web-widget-demos.readthedocs.io/en/latest/static_crm/tutorial/#installation-and-customization) to inject a script into my locally hosted app in a dev environment. 

It appears to me that the embed code is trying to post back to the local ringcentral iframe and hitting a security issue. 

**Questions**
1. Does this error even matter? 
2. If yes to q1, do i need to host the embed code locally within my application to avoid this? 
3. If yes to q2, I assume i need to copy the same redirect code on github and host that locally too?

Any advice appreciated. 

Thanks,

-S. Arora

**Comment by sarora2073** [comment]
Update: I've tried changing the redirect to a custom one that I host, and am having that redirect page invoke the code documented here:

https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/customize-redirect-uri.md

I still get that same error however, and am not sure if that's normal. Any help sanity checking the implementation appreciated.

**Comment by embbnux** [comment]
Hi @sarora2073 Can you provide screenshots that you got errors. Do you have any issues when you are using this widget.

The widget is a iframe hosted in `https://ringcentral.github.io`. So it is required to send  postMessage with:

```
postMessage(data, 'https://ringcentral.github.io') // set origin for security
```

If you want to host widget in your local server, you need to [rebuild](https://github.com/ringcentral/ringcentral-embeddable#deploy-on-production) the app to set HOSTING_URL

**Comment by embbnux** [comment]
It is recommended that you use our precompiled version in our Github page or CDN page.

**Comment by sarora2073** [comment]
Hi @embbnux, 

Thanks for the response. Screenshots are attached:

![image](https://user-images.githubusercontent.com/8941430/98839687-dadfa300-2413-11eb-94aa-f37dcbe629f2.png)
![image](https://user-images.githubusercontent.com/8941430/98839779-f64aae00-2413-11eb-9a20-9f2f1e245ea4.png)

I'm don't know if this error is going to cause issues or not. The widget "appears" to work (i.e. i can see it and dial out), but i'm having some issues trying to register a call logger, and want to be sure the embeddable is correctly intialized etc.

Thank you,

-S. Arora

**Comment by sarora2073** [comment]
update: i figured out the secondary issue for me -- the problem with registering the call logger.. i was trying it to invoke contentWindow.postMessage method to communicate upon script load, but i guess the frame isn't done loading just because the script is, so it was failing. 

That said, I don't know of any impact of the error above, or whether its benign. Closing for now.
