### ISSUE TITLE
Many js files not found and not sign in to the app on sandbox

### ISSUE THREAD

**Issue by Sanj718** [ringcentral/ringcentral-embeddable#472]
For some reason i cannot login to the ringcentral widget. Everything was fine till yesterday. 
Sometimes i see that some js/map files not found. 
Is there anything changed?

![image](https://user-images.githubusercontent.com/7362855/105044142-5ec99300-5a34-11eb-86f6-1152275f6020.png)

**Comment by embbnux** [comment]
Hi @Sanj718 The sandbox environment has issue now. Our engineer is working on this.

**Comment by Sanj718** [comment]
> Hi @Sanj718 The sandbox environment has issue now. Our engineer is working on this.

Thank you, please keep us posted :)

**Comment by embbnux** [comment]
Sure. Thanks so much for reporting this.

**Comment by embbnux** [comment]
@Sanj718 I can login with sandbox account now. Can you help to try at your side?

**Comment by Sanj718** [comment]
@embbnux Yes, its signing in but after couple seconds on widget it's loggin out and showing "Sign in" button again with "Webphone registerd" popup.

**Comment by embbnux** [comment]
@Sanj718 Can you help to check if you open multiple tabs with this widgets with different config (client id, server). Other tabs with this widget with different config will logout it.

**Comment by Sanj718** [comment]
@embbnux Yes it works on incognito window. :) but do you know is there any way to force to quit from all widget accounts?

**Comment by Sanj718** [comment]
I think it works now, just cleaned all cookies and cache. @embbnux thank you.

**Comment by embbnux** [comment]
> @embbnux Yes it works on incognito window. :) but do you know is there any way to force to quit from all widget accounts?

Once you logout in a tab, all tabs in same domain will be logout. From different browsers, you can logout at service.devtest.ringcentral.com to revoke access token for this app.
