### ISSUE TITLE
Need to support office@hand (ringcentral.biz) via embeddable

### ISSUE THREAD

**Issue by mbrindam** [ringcentral/ringcentral-embeddable#480]
We are currently using the ringcentral embeddable in our application to provide a dialer embedded in our application.  We need to also support, for some customers, the office@hand version of ringcentral through this embeddable.  Please provide a configurable option to switch between o@h or ringcentral proper.

**Comment by embbnux** [comment]
Hi @mbrindam you can follow here to have a full support for office@hand https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/multiple-brands.md#att-officehand

**Comment by embbnux** [comment]
We are also working on a solution to provide dynamic switching after user login. But it is still on experiment step:
```
https://ringcentral.github.io/ringcentral-embeddable/adapter.js?discovery=1
```

**Comment by embbnux** [comment]
close by inactive. Feel free to reopen it.
