### ISSUE TITLE
Refreshing a window with an i-frame holding the embeddable mutes sound.

### ISSUE THREAD

**Issue by tmLoyally** [ringcentral/ringcentral-embeddable#492]
The RC embedable works fine until someone refreshes their webpage, which mutes the audio, making users unable to hear the ringing for incomming calls. The audio will come back after the user has had some interaction with the embeddable, like clicking on a button or starting a call. 
 
It seems to be related to the audio policies used by Chrome (and other browsers):  https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

Adding an _allow="autoplay"_ to the I-frame html is not an option because we integrate the embedable into 3th party environments.

**Comment by embbnux** [comment]
@tmLoyally Good point. I will add `allow="autoplay"` into the widget iframe.
And I am not sure that you mention:

> Adding an allow="autoplay" to the I-frame html is not an option because we integrate the embedable into 3th party environments.

Can you give same example?

**Comment by embbnux** [comment]
@tmLoyally I tested iframe with "allow=autoplay; microphone". It can work well at Chrome. For Firefox, user still need to have interaction at top web page. For Safari, autoplay don't work well.

**Comment by embbnux** [comment]
Closed by inactive
