### ISSUE TITLE
Images in Messages

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable#50]
When someone sends a MMS text the images doesn't come across but the empty text blob is displayed. 
![image](https://user-images.githubusercontent.com/22582720/33280108-9a7db794-d366-11e7-9269-acb0767c89ba.png)

**Comment by embbnux** [comment]
Wait updating in RingCentral widgets library https://github.com/ringcentral/ringcentral-js-widgets/issues/900

**Comment by embbnux** [comment]
supported
