### ISSUE TITLE
How to by pass widget login 

### ISSUE THREAD

**Issue by harrishosp** [ringcentral/ringcentral-embeddable#500]
Hi,

we are trying to implement call center module using ringcentral widget on our web app , however its asking the end user to enter ringcentral creds manually , is there a way  we can by pass it and or send the creds internally . We don't want our users to know about the ringcentral creds. we are using developer sandbox to test the widget feature of the ringcentral..

**Comment by embbnux** [comment]
Hi @harrishosp We implement this widget with OAuth 2.0 which requires user to login in a popup window for security.
To hide ringcentral creds, you can try to enable SSO login in RingCentral service. So your user can login with Single Sign-On at login popup window. But I am not sure if you can enable SSO at sandbox environment.
https://support.ringcentral.com/article/6748.html
![image](https://user-images.githubusercontent.com/7036536/113959390-5c1d5380-9855-11eb-9585-7623233d2308.png)

**Comment by harrishosp** [comment]
Thanks @embbnux for the update. we will stick to the existing feature.  Is there any config settings to make this work on the hosted server using sandbox details.because the widget works fine in local env. however fails to work when hosted the application in the server. Any Clue about it ?

**Comment by embbnux** [comment]
> Thanks @embbnux for the update. we will stick to the existing feature. Is there any config settings to make this work on the hosted server using sandbox details.because the widget works fine in local env. however fails to work when hosted the application in the server. Any Clue about it ?

Do you mean that you want to let other people test in sandbox environment?
You can set appServer in query to change default environment for all users https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md#adapter-js-way

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
