### ISSUE TITLE
How to get access token and refresh token when user logins using the widget?

### ISSUE THREAD

**Issue by Krishnajha25** [ringcentral/ringcentral-embeddable#510]

**Comment by embbnux** [comment]
Hi @Krishnajha25 Token is saved at Browser localStorage with key "sdk-rc-widgetplatform". You can only access it when your deploy the app in your domain. But it is not recommended to use token, token will be expired and changed when the app refresh it.
If you want to manage token in server side, you can have a look at RingCentral proxy project, it make authorization in server side https://github.com/ringcentral/ringcentral-embeddable/issues/349

**Comment by embbnux** [comment]
closed by inactive. Feel free to reopen it.

**Comment by embbnux** [comment]
> Hi @Krishnajha25 Token is saved at Browser localStorage with key "sdk-rc-widgetplatform". You can only access it when your deploy the app in your domain. But it is not recommended to use token, token will be expired and changed when the app refresh it.
> If you want to manage token in server side, you can have a look at RingCentral proxy project, it make authorization in server side #349
