### ISSUE TITLE
Audio issues with embeddable

### ISSUE THREAD

**Issue by afowler-godaddy** [ringcentral/ringcentral-embeddable#523]
We have seen some issues with input/output audio not working with the Ringcentral embeddable. Unfortunately, I do not have any error logs on the browser for this. So far, we have seen this issue only on FireFox. Is FireFox fully supported?

**Comment by embbnux** [comment]
Hi @afowler-godaddy We have some known issues at Firefox when multiple tabs support is enabled:
https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/multiple-tabs.md#known-issues
https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/multiple-tabs.md#known-issues-1
And for Firefox, user can't select output audio device with Browser limitation.

Can you share more about what happen for input/output audio, how you reproduce this issue. And logs are appreciated. You can collect logs with Firefox developer console opened.

**Comment by afowler-godaddy** [comment]
Hi @embbnux , thanks for the information! 

I have unfortunately been unable to reproduce the issue, but we have had reports of these issues from our customers. We got on a call with them & some employees from RingCentral, and was directed here to inquire about Firefox. 

During the call, no logs of importance were output to the developer console. To reproduce, they:
- loaded the embededdable
- ensured that their Jabra headset was the connected audio device
- tried making an outbound call 
- noticed that neither she nor the receiver could hear any audio

**Comment by embbnux** [comment]
Thanks so much @afowler-godaddy for clarification. Did those issues happened recently? I got mention that we have Firefox audio issue at 4/30, and fixed at 4/30. 

And can you help to collect Firefox version information from your customer who has this issue, and browser HAR file if your users can still reproduce issue. They can help us to track issue.
To collect full HAR file, user need to open Firefox developer tool firstly, then reload the page to reproduce the issue. And any logs at developer console are also helpful.

**Comment by embbnux** [comment]
Hi @afowler-godaddy Do your users still get some issues. For HAR file and logs, please send it to "devsupport@ringcentral.com"

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it
