### ISSUE TITLE
Cannot embed stable versions with Telus branding

### ISSUE THREAD

**Issue by benlinzel** [ringcentral/ringcentral-embeddable#535]
For example, using v1.7.0, it attempts to load styling from [here](https://apps.ringcentral.com/integration/ringcentral-embeddable/1.7.0/app.telus.css), but fails.

**Comment by embbnux** [comment]
Thanks @benlinzel We have got the root cause. It is issue from our CI job from stable release. I will update missing branding file manually to fix it.

**Comment by embbnux** [comment]
Hi @benlinzel It is fixed at 1.7.0 release now

**Comment by benlinzel** [comment]
Thanks @embbnux ! Works great now 👍

**Comment by embbnux** [comment]
Thanks for confirming @benlinzel will close it.
