### ISSUE TITLE
Popup call drops if main window is reloaded/closed

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#536]
We're excited to adopt the popup functionality as it will help our users in some particular situations.  We're evaluating the popup functionality and have found an issue.

We're using version 1.7.0 of the embeddable following these for enabling popup [docs](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/popup-window.md)
We tested in Chrome Version 91.0.4472.106
Calling mode is set to Browser.

Steps to reproduce the issue:
1. Popup the embeddable into a separate window.
2. Start a call.
3. Reload or close the main tab where the popup was launched

Expected: Call continues in the popup.
Actual: The call is dropped.

**Comment by embbnux** [comment]
Thanks for feedback @ElridgeDMello It should be a bug. Will fix it soon.

**Comment by embbnux** [comment]
Hi @ElridgeDMello Do you host popup HTML by your self, and add all code in https://github.com/ringcentral/ringcentral-embeddable/blob/master/src/popup.html:

```js
window.__ON_RC_POPUP_WINDOW = 1;
```

Actually when I tested, I can't reproduce in my side.

**Comment by ElridgeDMello** [comment]
No, we do not host the popup.html code ourselves.  We're loading the embeddable via [option 1](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/popup-window.md#to-enable-this-feature):

```javascript
<script>
  (function() {
    var rcs = document.createElement("script");
    rcs.src = "https://apps.ringcentral.com/integration/ringcentral-embeddable/1.7.0/adapter.js?enablePopup=1";
    var rcs0 = document.getElementsByTagName("script")[0];
    rcs0.parentNode.insertBefore(rcs, rcs0);
  })();
</script>
```

**Comment by embbnux** [comment]
Thanks for confirming @ElridgeDMello Let me check again

**Comment by embbnux** [comment]
Hi @ElridgeDMello I still can't reproduce it with same code that you provide. Do you set other flags in `adapter.js` URI?

Can you help to collect logs or other screenshots, videos if you can still reproduce it? You can send them to our Dev Support email.

**Comment by ElridgeDMello** [comment]
> Hi @ElridgeDMello I still can't reproduce it with same code that you provide. Do you set other flags in `adapter.js` URI?
> 
> Can you help to collect logs or other screenshots, videos if you can still reproduce it? You can send them to our Dev Support email.


Yes, we have additional params:
`enableFromNumberSetting=1&disableActiveCallControl=false&disconnectInactiveWebphone=1&disableConferenceCall=false&enablePopup=1`

I am able to reproduce the issue.  I emailed requested details to RC Dev Support Email address.

**Comment by embbnux** [comment]
Thanks @ElridgeDMello Got you email. Will keep you updated

**Comment by embbnux** [comment]
Hi @ElridgeDMello Found the root cause. You need to change `disconnectInactiveWebphone=1` into `multipleTabsSupport=1` to have popup feature work well. I will update docs about this.

**Comment by ElridgeDMello** [comment]
Ok, thanks, verified that it works as described with the `multipleTabsSupport=1` flag set!
