### ISSUE TITLE
Opening popup while on a call drops the call

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#540]
We're using version 1.7.0 of the embeddable following these for enabling popup docs
We tested in Chrome Version 91.0.4472.106
Calling mode is set to Browser.

Steps to reproduce the issue:
1. Start a call
2. Popup the embeddable into a separate window

Expected: Call continues in the popup.
Actual: The call is dropped.

**Comment by embbnux** [comment]
Thanks @ElridgeDMello We can reproduce it now. And add this bug into backlog.

**Comment by embbnux** [comment]
Hi @ElridgeDMello Still on hold now. As technical limtation from browser, we can only send notification to user when user want open popup window with active call. So user can only open popup window when there are not calls.

**Comment by embbnux** [comment]
I am going to close this. Feel free to reopen it if you still need it.
