### ISSUE TITLE
Question: Ability to query active call state?

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#541]
Does the embeddable provide consuming applications the ability to query/ask for active calls state?

This would be a great feature to be able to synchronize state in use cases such as:

* Company wide aggregation of all users calls (without having to build a backend/API integration with Ringcentral)

**Comment by embbnux** [comment]
Hi @ElridgeDMello Currently Embeddable is built at extension (user) level. So it can't provide all users calls. 
As RingCentral provide company level call log API, it is recommended to use it to query all users calls.  You can try my ringcentral-presences-monitor app to get all users active calls for admin user. https://medium.com/ringcentral-developers/building-a-presences-and-calls-monitor-app-with-ringcentral-apis-976eb1fa6763
