### ISSUE TITLE
All statuses except "Do not disturb" are displayed as "Invisible"/Offline. Even when I selected "Available"

### ISSUE THREAD

**Issue by duyendoan** [ringcentral/ringcentral-embeddable#542]
When I changed the status on the embeddable dial pad to "Available"/"Busy"/"Invisible", it's all displayed as "Invisible" (gray icon). This issue occurred recently

**Comment by embbnux** [comment]
Hi @duyendoan , can you help to collect Browser logs and network HAR to hep us track this issue. 

To collect logs and HAR, you need:
1. Right click page and Inspect to open Chrome developer tool.
2. Reload the page with embeddable to reproduce this issue
3. In Chrome developer tool Console panel, right click to select "Save as" to save logs.
4. In Chrome developer tool Network panel, right click to select "Save as HAR" to save HAR.

Then provide logs and HAR in https://developers.ringcentral.com/support/create-case

**Comment by duyendoan** [comment]
@embbnux Thanks for your instruction. It also happens to my other dev account. I submitted a case with logs and HAR using the link you provided.

**Comment by embbnux** [comment]
Replied at email. Root cause is that the user turn off "Allow other users to see my presence" at RingCentral service web page. So the widget can't change userStatus.
