### ISSUE TITLE
E911 Address Validation Errors not correctly communicated to users

### ISSUE THREAD

**Issue by Brutalbeard** [ringcentral/ringcentral-embeddable#557]
Sitel was having issue with their E911 addresses being validated when logging in. It would seem the issue was caused by the provider in the UK that validates addresses, not an issue with the embeddable. 

What was an issue for the user was the error toast that would pop up on screen. Customer didn't have a way to read that, and understand that the address they were trying to use was invalid. 

![image (2)](https://user-images.githubusercontent.com/7102792/133455956-fdf926be-ac14-4f01-9cd2-03b8d8a57d85.png)

**Comment by Brutalbeard** [comment]
Not sure if the failure response from platform would indicate that the address simply failed, but if it does, we should relay that.

**Comment by embbnux** [comment]
Closed as this is not issue at embeddable.
