### ISSUE TITLE
Support to change output device for ringing audio

### ISSUE THREAD

**Issue by ashleycorinnex** [ringcentral/ringcentral-embeddable#559]
When I go to the audio settings and try to change my output device, it doesn't listen to what I chose. It always chooses my Windows default device as the output audio. Am I missing something or is this a real bug? 
![Audio](https://user-images.githubusercontent.com/46426941/134556957-5706a859-0ef1-4b2c-aa9a-ede0fb625ece.PNG)

**Comment by embbnux** [comment]
Hi @ashleycorinnex The widget doesn't support to set output device for ringing audio. Can you check if you have this issue at ringing audio or call audio?

**Comment by ashleycorinnex** [comment]
Oh I see, yes I was only testing the ringing audio. Are there any plans to fix that in a future release? I would expect the output device to honor my ringing audio too.

**Comment by embbnux** [comment]
@ashleycorinnex Thanks for confirming this. It is on our backlog. I will update here once it has release timeline.

**Comment by ashleycorinnex** [comment]
Great, thank you!

**Comment by embbnux** [comment]
supported with #828 in 2.x
