### ISSUE TITLE
Allow `disableMinimize` config like `disableSMS`

### ISSUE THREAD

**Issue by benlinzel** [ringcentral/ringcentral-embeddable#567]
In the event that an application embeds the widget and wants custom UI handling for the widget, the minimize functionality should be configurable to keep from interfering with custom UI handling in the host application.

**Comment by embbnux** [comment]
Thanks @benlinzel It is good idea. Added it into backlog.
For now, you can use `RCAdapter.setMinimized(false)` to make it un-minimized.

**Comment by embbnux** [comment]
Supported at master build https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/disable-features.md#disable-the-widget-minimized

**Comment by CoCraig** [comment]
@benlinzel can you explain why you wish to remove the minimize button?  I'm not clear how this interferes with custom UI handling.

**Comment by benlinzel** [comment]
Basically if the RC widget is embedded in another application, and that application contains its own UI button or custom event handling to show/hide the fullscreen widget, it confuses users when there's also a third state (visible but minimized)

**Comment by embbnux** [comment]
Closed this as we supported at 1.8.0
