### ISSUE TITLE
Question: can we depend on RCAdapter.popupWindow

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#568]
Hi @embbnux ,

I see this method exposed on the `RCAdapter` object: `RCAdapter.popupWindow`.

We would like to control the popup programmatically, but I don't see this method documented in the [docs to control the widget](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md) so I wanted to confirm it is safe to depend on it.  Can we depend on this method being supported?  We're planning to use it starting in version 1.7.2.

Thanks!

**Comment by embbnux** [comment]
Hi @ElridgeDMello It is safe to use it. It is public API of `RCAdapter`.
And it is recommended to use 1.7.3 as we have bugfixs at that

**Comment by embbnux** [comment]
Added it into docs https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#popup-the-widget
