### ISSUE TITLE
feature request: RCAdapter.isWindowPoppedUp

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#570]
Hi @embbnux,

We are using the `RCAdapter.popupWindow` method to popup the embeddable.  Our app has various entry points, but shares a root layout that we use for load the embeddable, wait for `window.RCAdapter` to be available, then call `RCAdapter.popupWindow`. 

This invocation of the `RCAdapter.popupWindow` on the root layout can be called multiple times during a user navigating various pages in the app.  Calling this method when the window is already popped up renders a warning message in the UI, which can be distracting to the user, and cause warning blindness in the future.  The user would not understand why they are seeing this warning periodically while navigating through our app.
It would be useful to have a `RCAdapter.isWindowPoppedUp` method that we can use to check if the embeddable is already popped to make a decision on whether to call the `RCAdapter.popupWindow` method.

Alternatively, could add a boolean flag that we can pass in to not show the warning message if desired e.g. `RCAdapter.popupWindow({ showAlreadyPoppedUpWarning: false })`

I think the `RCAdapter.isWindowPoppedUp` might be better as it may be useful in other situations too.

Thanks!

**Comment by embbnux** [comment]
Hi @ElridgeDMello This is good feedback. Added it into backlog.

**Comment by embbnux** [comment]
Supported at master build https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/popup-window.md#to-check-if-popup-window-opened

**Comment by ElridgeDMello** [comment]
> Supported at master build https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/popup-window.md#to-check-if-popup-window-opened

Thanks @embbnux for this enhancement from 1.8.0.

Couple of questions:

1. Do you know when that release is scheduled to go out?
2. Are you still classifying this feature (pop out embeddable) as a beta feature, or is it stable/production ready at this point?

**Comment by embbnux** [comment]
> > Supported at master build https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/popup-window.md#to-check-if-popup-window-opened
> 
> Thanks @embbnux for this enhancement from v1.8.0.
> 
> Couple of questions:
> 
> 1. Do you know when v1.8.0 is scheduled to be released?
> 2. Are you still classifying this feature (pop out embeddable) as a beta feature, or is it stable/production ready at this point?

Hi @ElridgeDMello  Actually I am going to release 1.8.0 today. And we pop-out feature will go to stable from 1.8.0

**Comment by embbnux** [comment]
1.8.0 released

**Comment by embbnux** [comment]
Closed as 1.8.0 released. Feel free to reopen it here if you get related issues.
