### ISSUE TITLE
Error when triggering startRecord call action for outgoing calls

### ISSUE THREAD

**Issue by mangatinanda** [ringcentral/ringcentral-embeddable#579]
I am trying to trigger call recording using the below code when I receive event `rc-call-start-notify`:
```
document.querySelector("#rc-widget-adapter-frame").contentWindow.postMessage({
  type: 'rc-adapter-control-call',
  callAction: 'startRecord',
  callId: `call id`
}, '*');
```
It is failing sometimes for an outbound call and I am seeing a console error:
```
{code: -4, description: 'State is not accepted for processing'}
```
Since I do not know if this action has failed I can't retry as well. 

Is it recommended to trigger call recording after some delay(say 5sec)?

**Comment by embbnux** [comment]
Hi @mangatinanda Actually, we can not make sure the delay time. For some phone system, they request caller to input extension number to make call connected. We can't start demand recording before that.
If you want to implement auto recording, you can tell your RingCentral account admin to enable auto recording at RingCentral service portal  https://support.ringcentral.com/article/10665-automatic-call-recording-enable-disable.html

**Comment by mangatinanda** [comment]
Thanks for the explanation @embbnux
