### ISSUE TITLE
Can't get voice for incoming call at Safari iPadOS 15

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable#580]
When user accept incoming call at Safari iPadOS 15, the caller fail to get voice from the ipad user

**Comment by embbnux** [comment]
Related https://developer.apple.com/forums/thread/689293

**Comment by byrnereese** [comment]
@embbnux Is this still an issue?

**Comment by embbnux** [comment]
Not. Just try, it works well at iPadOS 16.3. Need user to upgrade iPadOS for full webRTC support.
