### ISSUE TITLE
Recording conference calls.

### ISSUE THREAD

**Issue by mangatinanda** [ringcentral/ringcentral-embeddable#586]
I am facing two issues w.r.t call recording of conference calls.

1. When the call recording is on, I am not able to add a new call. Not sure if this is a limitation in the API but it shows an error asking to stop the recording and try again.  
![Screenshot 2021-12-21 at 12 19 37 PM](https://user-images.githubusercontent.com/6745155/146885315-27e35ac4-1a73-462f-9a1c-4289bebde05d.png)

2. While in the conference call, clicking on the record button throws 409 conflict error. 
<img width="291" alt="Screenshot 2021-12-20 at 4 31 24 PM" src="https://user-images.githubusercontent.com/6745155/146885458-1a2cc80d-3850-4915-af97-8f2acfec13bd.png">

**Comment by embbnux** [comment]
Hi @mangatinanda For 1, it is by design. We can't add someone into a recorded call.
For 2, let me check with team

**Comment by embbnux** [comment]
supported at v1.8.8
