### ISSUE TITLE
Enable Glip feature not working

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#588]
Hello,

We are trying to use glip/team messaging via the embeddable.

Our URL to load the RC Embeddable via the adapter way is: https://apps.ringcentral.com/integration/ringcentral-embeddable/1.8.0/adapter.js?clientId=myClientId&appServer=https://platform.devtest.ringcentral.com&enableFromNumberSetting=1&disableActiveCallControl=false&disconnectInactiveWebphone=1&disableConferenceCall=false&disableGlip=false

We did add the 'Team Messaging' permission to the developer app.

We do not get any network/console errors on embeddable load, **but** we also do not see glip/team messaging in the embeddable:

![image](https://user-images.githubusercontent.com/1136153/148085057-80ddd628-f788-4f59-92a1-c87734e722f3.png)

![image](https://user-images.githubusercontent.com/1136153/148085123-0e0711f7-d7f4-4fb3-93f8-c0c81d660863.png)

Where would we expect to see the glip feature in the embeddable?

**Comment by embbnux** [comment]
Hi @ElridgeDMello Can you check if there are any errors at chrome console? It will not show team messages if user doesn't have permission. And for sandbox user, user need to login into https://app.devtest.ringcentral.com firstly.

**Comment by ElridgeDMello** [comment]
> Hi @ElridgeDMello Can you check if there are any errors at chrome console? It will not show team messages if user doesn't have permission. And for sandbox user, user need to login into https://app.devtest.ringcentral.com firstly.

That was it, needed to first login to  https://app.devtest.ringcentral.com.

Submitted documentation update PR: https://github.com/ringcentral/ringcentral-embeddable/pull/590
