### ISSUE TITLE
v1.8.0 throwing permissions errors for not opted in features

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#591]
Trying v1.8.0 in our Prod environment, found some endpoints are being called that are returning `401` status codes.  

These permissions expected, which we do not have setup in our developer app (as we did not opt in for these features):
`TeamMessaging`
`Meetings`

e.g. 
```
{
  "errorCode" : "InsufficientPermissions",
  "message" : "In order to call this API endpoint, application needs to have [Meetings] permission",
  "errors" : [ {
    "errorCode" : "CMN-401",
    "message" : "In order to call this API endpoint, application needs to have [Meetings] permission",
    "permissionName" : "Meetings"
  } ],
  "permissionName" : "Meetings"
}
```

App is loaded the adapter way via this URL:
https://apps.ringcentral.com/integration/ringcentral-embeddable/1.8.0/adapter.js?clientId=myClientId&appServer=https://platform.ringcentral.com&enableFromNumberSetting=1&disableActiveCallControl=false&multipleTabsSupport=1&disableConferenceCall=false&enablePopup=1

It does not *seem* to be negatively impacting the functionality of the app but it is disconcerting to see these network errors and console logs.

I will shortly email devsupport@ringcentral with network and console log files.

**Comment by embbnux** [comment]
fixed at v1.8.11
