### ISSUE TITLE
Question: how to disable/minimize log verbosity?

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#596]
Hi @embbnux,

Is there a way to reduce the verboseness of the console.log messages written by the embeddable?

We also notice quite a few warnings in the console when the embeddable is loaded.

![image](https://user-images.githubusercontent.com/1136153/151454859-f6c3d678-eb67-44c5-a404-09795b8c716e.png)

Thanks in advance!

**Comment by embbnux** [comment]
Hi @ElridgeDMello It is deprecated warning in our widgets lib. I will upgrade modules to remove those warning.

**Comment by byrnereese** [comment]
I am going to resolve this as a duplicate of a similar request. Our plan is to introduce a loglevel setting that someone can set. That will allow one to throttle how many messages are output to the console.
