### ISSUE TITLE
No option to hold the second inbound call from the browser while user is on the first call initiated from the RC app

### ISSUE THREAD

**Issue by duyendoan** [ringcentral/ringcentral-embeddable#600]
I'm on a call on the RC web app. There is another inbound call and it rings in both RC embeddable widget and the web app (as expected). However, there is no option to put it on hold on the widget. The option only shows in the web app.

**Comment by embbnux** [comment]
Hi @duyendoan The option to put second call on hold is only supported when you have calls on same device. As the RC web app and this widget are independent apps (devices), so the widget doesn't show the option.
