### ISSUE TITLE
Question/feature request to get active call status

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#604]
We are using the widget popout functionality in our app.  We use the events from the widget to render a hangup button in our app.  When our main app refreshes, the call stays on (which is very good 👍 ) but due to the refresh we lose the state in the app for knowing whether we're currently on a call (and the app does not have a hangup button).

Question/Feature Request:
Is there a way to programmatically get the current status of all active calls?  If not, would it be possible to prioritize a feature that allows this?

**Comment by embbnux** [comment]
Hi @ElridgeDMello We have supported this at master build. Can you help to try it with this [doc](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#web-phone-sessions-sync-event)?

**Comment by embbnux** [comment]
supported with v1.8.3
