### ISSUE TITLE
version 1.8.1 - Ringcentral App calling mode opens browser tab on new call

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#605]
When calling mode is set to RingCentral App, when we programmatically start a call, a new tab is opened with instructions to download the app (even though we already have it).  

The actual call is placed and works as expected, but opening a new tab with these confusing instructions on every call initiation is problematic;  It would be especially problematic for users that already have the app installed and creates a confusing experience for our users; We cannot roll this out to our entire userbase as we need to support both browser/RingCentral app calling modes.

Screenshots that illustrate the issue:
![set-calling-mode-to-ringcentral-app](https://user-images.githubusercontent.com/1136153/155422297-f3a50eea-3e18-4f23-b544-39a799423643.png)

Programmatic call initiation by:
```
document.querySelector("#rc-widget-adapter-frame").contentWindow.postMessage({
  type: 'rc-adapter-new-call',
  phoneNumber: `+1520....`,
  toCall: true,
}, 'https://apps.ringcentral.com');
```

Starts the call correctly in the installed Ringcentral app.
But also pops open this new tab (on every call that is initiated):

![start-call-opens-new-tab](https://user-images.githubusercontent.com/1136153/155422973-8fa70d39-10a3-4c48-82f4-f218b6e08dda.png)

I can send over network .HAR log file and console log to devsupport@ringcentral for additional troubleshooting.

Operating System: Mac OS (Monterrey) version 12.1
Browser: Chrome 98.0.4758.102 (Official Build) (x86_64)
Ringcentral (app) Version:   22.1.20.341 Web, 22.1.11.2682 Mac (Intel)

**Comment by embbnux** [comment]
Hi @ElridgeDMello Thanks for the feedback. I can reproduce it in my side. Let me discuss with team about how to avoid the new tab.

**Comment by embbnux** [comment]
Hi @ElridgeDMello , we have an update at master build about this. Can you help to try it at https://ringcentral.github.io/ringcentral-embeddable/

**Comment by ElridgeDMello** [comment]
> Thanks @embbnux for the fix for this. I tried it out and the call was placed without a new tab being opened. I did encounter an issue with not seeing some expected events (e.g. call connected, hangup, etc). I will repro shortly with network log capture and email them over to the [devsupport@ringcentral.com](mailto:devsupport@ringcentral.com) account.

Re-tested today and it worked, so the fix is good! Thanks!  When can we expect this to be released?

**Comment by embbnux** [comment]
Thanks for confirming @ElridgeDMello . It should be released next week. I will check if we can add another enhancements into  this release. If there are not new PRs, it should be next week.

**Comment by embbnux** [comment]
@ElridgeDMello 1.8.2 released
