### ISSUE TITLE
Popup opening in new tab instead of popup window

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#610]
For one of our users, the Embeddable popup is opening in a new tab instead of in a popup window:

This is how the embeddable is being loaded:
`https://apps.ringcentral.com/integration/ringcentral-embeddable/1.8.1/adapter.js?clientId=myClientId&appServer=https://platform.ringcentral.com&enableFromNumberSetting=1&disableActiveCallControl=false&multipleTabsSupport=1&disableConferenceCall=false&enablePopup=1`

I will email network and console logs that were captured for this user to devsupport@ringcentral.com.

**Comment by embbnux** [comment]
hi @ElridgeDMello can you help to check with the user's browser extensions? There are some browser extensions which make browser popup window into new tab.

**Comment by ElridgeDMello** [comment]
Tried disabling all extensions but the issue still persists for this user.  Emailed network and console logs.

**Comment by embbnux** [comment]
Thanks @ElridgeDMello I got log files. But I don't see any related errors.
Can you let the user to run this code in your website's browser devtool to check if it can work: 

```js
window.open("https://ringcentral.github.io/ringcentral-embeddable/app.html", "RCPopupWindow", "scrollbars=yes, width=300, height=500")
```

I still think it is some settings at user browser to cause this issue as the widget just call `window.open` API from browser.

**Comment by ElridgeDMello** [comment]
When we tried to reproduce the issue, the popup opens in a new window as expected.  Not sure whether it was a chrome update that caused this behavior to change but we have not had any other users experience this.  Going to close this as resolved for now.  Will re-open if necessary. Thanks!
