### ISSUE TITLE
Getting "Web Phone Unavailable" for multiple users

### ISSUE THREAD

**Issue by arubyit** [ringcentral/ringcentral-embeddable#622]
We have checked permissions on both Edge and Google Chrome and are still getting "Web Phone Unavailable" as well as "Please grant RingCentral Embeddable to access your audio.". We have been using this extension for months and haven't had this issue before. Additionally, several users are experiencing this. We have tried multiple restarts, installs, rolling back the ringcentral extension version, reinstalling our audio device software. Nothing seems to be working. I've attached a screenshot of the error.

![image](https://user-images.githubusercontent.com/96540187/168346108-9fcc68ce-0d64-4e06-87bd-ecb26cb59d9d.png)
![image](https://user-images.githubusercontent.com/96540187/168346177-7881b9b4-9c5c-426d-a6de-db301fbbd808.png)

**Comment by embbnux** [comment]
Hi @arubyit can you help to check if microphone is enabled at following pages:

1. the page that embed the widget
2. https://ringcentral.github.io/ringcentral-embeddable/#
3. https://apps.ringcentral.com/integration/ringcentral-embeddable/

To check that, click secure icon that the browser address tool:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/7036536/168400191-a510fcaf-c5c5-44fe-a6d1-5a45f8f3df6f.png">


And can you also help to collect logs and HAR file to help us track this issue.

To collect logs and HAR file:
1. Right click the widget and select Inspect to open Chrome developer tool
2. Reload the page with the widget, then reproduce this issue
3. In Chrome developer tool: at console panel, right click logs to "Save as".
3. In Chrome developer tool: at network panel, right click requests to "Save All as HAR with content".
Then create a ticket here to submit those files https://developers.ringcentral.com/support/create-case, and post the ticket number or title here.

**Comment by embbnux** [comment]
Close this by inactive. Feel free to reopen it if you still have same issue.
