### ISSUE TITLE
Too many 429 errors

### ISSUE THREAD

**Issue by CoCraig** [ringcentral/ringcentral-embeddable#625]
We are seeing an ever increasing number of 429 errors due to the `oauth/token` API calls.  This rate limit error can be seen with the RingCentral for HubSpot Chrome Extension built by RC Labs and is likely due to how customers like to use many tabs in HubSpot and they are all trying to refresh the token at one time.

**Comment by embbnux** [comment]
Fixed with #623

**Comment by embbnux** [comment]
Closed this as we found it is issue at HubSpot Chrome Extension.
