### ISSUE TITLE
Question: Reason for different error rates vs webapp/desktop app?

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#639]
Our users mainly use the RingCentral Embeddable within our application for making click to dial calls.

They are reporting that the error rate on calls through the Embeddable are higher than compared to the [RC WebApp](https://app.ringcentral.com/) or RC Desktop App.  Here errors would be things like call drops, call does not connect/widget spins indefinitely.  Often times when these errors happen multiple times for a call, they switch to manually dialing via the Webapp or Desktop App. 

Is there a systemic reason this might be the case?  E.g. different backend services used by the different applications?

**Comment by embbnux** [comment]
Hi @ElridgeDMello Can you help to collect logs and HAR from users, so we can track that errors.

For compared to RC app, actually they are using same web phone SDK, but some differences:

1. The widget supports multiple tabs,  so they are some reconnection when user switches page. 
2. RingCentral app is official app, so it has higher API rate limits.
3. Different API endpoint domain. And sip server domain is different by different users and apps. 
4. Official app may use some internal APIs.

BTW in the widget, user can change the calling mode to "Make call with RingCentral app". So they can start call from this widget, but have call audio at RingCentral app and still get call events in the widget.

**Comment by embbnux** [comment]
closed by inactive. Feel free to reopen it.
