### ISSUE TITLE
Toggle to mute ringtone

### ISSUE THREAD

**Issue by DaKingKong** [ringcentral/ringcentral-embeddable#640]
Use case:

User has other phone devices, and would like to mute embeddable's  ringtone while taking on others.

Existing way/workaround to mute ringtone is to upload a silent audio as ringtone, which needs several clicks. Ideally, the new toggle would be more easily accessible as it's gonna be frequently used by users with multiple devices.

**Comment by DaKingKong** [comment]
Another use case that might make more sense.

User already in a phone call and another incoming call happens. According to user feedback, the incoming call's ringtone will go off.

I guess what we want to do is:
1. Confirm the case
2. Maybe implement it as a toggle in user setting to silent ringtone while during phone call.

**Comment by embbnux** [comment]
Duplicated with #650 , supported with https://github.com/ringcentral/ringcentral-embeddable/pull/656
