### ISSUE TITLE
How to reinitialize ringcentral widget after dispose

### ISSUE THREAD

**Issue by jinalptl1993** [ringcentral/ringcentral-embeddable#641]
I am integrating the RingCentral widget in my react js application. I need to display it for the specific route. When I first time visited that page, It is working just fine. On route change(component destroy) I am using RCAdapter.dispose(); to do not display(destroy) RingCentral widget.

Now, when I revisit that route, that RingCentral widget is not getting reinitialized. RingCentral is not getting displayed.

Few points to note here,
1. I am using RCAdapter.dispose();. **On alternative I tried to use RCAdapter.setClosed(true);. But in that case, widget is not getting displayed, but when I get call, It's ringing and there is no control for me to receive/decline a call** until and unless I go to a specific route(page).
2. After using, RCAdapter.dispose(); I didn't find any way to re-initialize the widget.

Thanks a lot in advance!

**Comment by embbnux** [comment]
Hi @jinalptl1993 Good point! Currently the app can't be re-initialized after disposed. We can add the API, and can you help to check following question, so we can know what you want:

1. Do you need user to receive the call when user redirect to other routes. For `RCAdapter.setClosed(true)`, it just hide the widget, you can listen to  new call event and set closed false to open the widget again.

**Comment by jinalptl1993** [comment]
@embbnux First of all, thanks a lot for your quick response.

1. My initial use case just does not receive calls when the widget is not displayed. But I am fine If somehow I would be able to open the widget If I receive any call If there is no other option.
2. It would be great If I will have control over initialization then I would be able to initialize it whenever I need.

I hope I provided enough details.

Once again, Thanks for your response!

**Comment by embbnux** [comment]
@jinalptl1993 you are welcome! Let me add the option to initialize the app. 

For open the widget when you receive call, you can listen to [ringing event](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#web-phone-call-event) and `setClosed(false)`.

**Comment by jinalptl1993** [comment]
Thanks a lot @embbnux 

Meanwhile, I am trying with [ringing event](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#web-phone-call-event) and setClosed(false).

**Comment by embbnux** [comment]
Hi @jinalptl1993 we have release a new build at Github page version. You can follow the doc to init and dispose manually
https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/adapter-init.md

**Comment by jinalptl1993** [comment]
Thanks a lot, @embbnux for all your help!

I am excited to use this option!

**Comment by embbnux** [comment]
You are welcome. When it goes well some days, we will release this into our CDN build.

**Comment by embbnux** [comment]
Released with v1.8.5
