### ISSUE TITLE
Warning: old Embeddable widget may have issue to receive transfer call

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-embeddable#649]
We receives report that user with old embeddable widget may fail to answer transferred call.
The old embeddable widget use old web phone SDK causing this issue.

Upgrade Embeddable to v1.8.5 can fixed this.

**Comment by byrnereese** [comment]
Thank you for the alert. This issue has been fixed as you pointed out. We are going to close this issue out.
