### ISSUE TITLE
Hide contacts tab

### ISSUE THREAD

**Issue by sahil-infocusp** [ringcentral/ringcentral-embeddable#662]
I don't have given access to `ReadContacts` and `ReadCallLog` to my app, but the widget keeps calling that api and error gets logged to console. Is there any way to disable contacts and call-logs functionality? And hide that tab from the widget?
![image](https://user-images.githubusercontent.com/73810410/207226286-47326569-6eb8-48e4-bf10-aef141bffbc2.png)

**Comment by embbnux** [comment]
Hi @sahil-infocusp It should auto hide contacts and call history tab. It is a bug and will be fixed soon.

**Comment by embbnux** [comment]
Okay, contacts tab has data from call queue and company contacts (extension users) and personal contacts. The ReadContacts permission is only for  personal contacts. So app will not hide the tab if it doesn't has ReadContacts permission.
I added the flag "disableContacts" to hide the tab in #663 . After it merged, you can use flag to hide contacts. And call history will auto be hidden if app doesn't has ReadCallLog permission.

**Comment by sahil-infocusp** [comment]
Awesome, thanks for quick updates.
