### ISSUE TITLE
Disable incoming calls

### ISSUE THREAD

**Issue by sahil-infocusp** [ringcentral/ringcentral-embeddable#665]
Is there an option to disable all the incoming calls in the widget? I tried setting DnD but it also disables in the actual ring-central app. Can we disable incoming calls just in the widget?

**Comment by embbnux** [comment]
hi @sahil-infocusp you can change calling setting into call with RingCentral app. And the widget will not receive the incoming call.

**Comment by sahil-infocusp** [comment]
@embbnux : How can I change calling setting so that I do not get notified about incoming calls in the widget but I can place outgoing calls using widget? 
Also is there any way to do it programmatically?

**Comment by embbnux** [comment]
In app, it is Settings page -> Calling Settings.
For api, you can follow here https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/interact-with-calling-settings.md

**Comment by embbnux** [comment]
Close this by inactive. Feel free to reopen if you still need it
