### ISSUE TITLE
Need more events subscription

### ISSUE THREAD

**Issue by DaKingKong** [ringcentral/ringcentral-embeddable#672]
Need 4 events as below:
1. Send SMS
2. Change user settings (eg. toggle on/off auto call log)
3. Change user status (eg. from Available to Busy)
4. Scheduled a meeting

**Comment by embbnux** [comment]
For user status, you can using presence sync event: https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/widget-event.md#presence-sync-event

**Comment by embbnux** [comment]
For other event, please follow here https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/add-analytics.md#enable-analytics
