### ISSUE TITLE
Possible to customize popup window title?

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#678]
Is it possible for our application to customize the title of the Popup window?  It currently reads as "RingCentral Embeddable" but we would like to customize it.

![RingCentral_Embeddable_and_Welcome](https://user-images.githubusercontent.com/1136153/222494953-2af7729a-501e-4845-9c73-9d02db58b3b7.png)

**Comment by embbnux** [comment]
Hi @ElridgeDMello You can host the popup page HTML with yourselves https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/popup-window.md#host-the-popup-window
So you can change the title.

**Comment by embbnux** [comment]
Close this as inactive. Feel free to reopen it.
