### ISSUE TITLE
No audio using widget?

### ISSUE THREAD

**Issue by MattHoneycutt** [ringcentral/ringcentral-embeddable#679]
Hi there,

We have integrated the RingCentral widget into our application.  We have some users that are able to make a call using the widget, but they aren't getting an audio.  The person using the widget can't hear anything, and the person on the other end of the call can't hear anything.  When we check the recording, we can hear the person on the other end of the call, but nothing from the person that made the call using the widget.

Relevant info:
Windows 11
Chrome (latest version)

Things we've verified and tried:
* The user has granted microphone permissions to our web app
* The correct input and output device is selected in the widget's settings
* The device works fine with the RC desktop app as well as other apps, like Zoom.
* We've tried restarting the browser, restarting the computer, etc.

What else can we check?

**Comment by embbnux** [comment]
Hi @MattHoneycutt You can also check app logs in Chrome developer tool console and webRTC in chrome://webrtc-internals/

And does this happen always in the user's computer? It that, can you help to collect those data, and send them to https://developers.ringcentral.com/support/create-case

1. app log in developer tool console panel
2. HAR file in developer tool network panel (right click at request to save all as HAR with content)
3.  WebRTC Dump log  and "Stats graphs for transport" screenshot in `chrome://webrtc-internals/` page

To collect full data, user need to open developer tool and `chrome://webrtc-internals/` firstly, then logout app and login to reproduce the issue.

**Comment by embbnux** [comment]
I am going to close this as inactive. Feel free to reopen this if you get the issue again.
