### ISSUE TITLE
[feature request] Display Avatar images alongside Contact data

### ISSUE THREAD

**Issue by workbooks** [ringcentral/ringcentral-embeddable#682]
Attributes returned to contact/search and contact/match include name, jobTitle, company, email and phoneNumbers. The widget does show an avatar placeholder within the Contacts tab.

I'd like to be able to return to the widget a URL to an avatar image which would be displayed alongside the name of the contact in the Contacts tab.

**Comment by embbnux** [comment]
Closed this as inactive. Feel free to reopen it.
