### ISSUE TITLE
Disable inbound ringing when using the embedded widget?

### ISSUE THREAD

**Issue by MattHoneycutt** [ringcentral/ringcentral-embeddable#683]
We have the RC widget embedded into our app, but we are explicitly not doing anything with inbound calls yet.  We have a lot of integration built out for outbound calls though.  Is there a way to prevent the widget from ringing when the associated digital line receives an inbound call?  We still want the user to get the "ring" through their desktop app like they have previously done.

**Comment by embbnux** [comment]
Hi @MattHoneycutt User can change the calling mode to RingOut or make call with RingCentral desktop app. With that mode, the widget will not ring. You can also change the default calling mode https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/interact-with-calling-settings.md#interact-with-calling-settings.

**Comment by MattHoneycutt** [comment]
Thanks @embbnux , but I don't think that will give us what we want here.  We want outbound calls to use the in-app widget fully.  We just don't want the widget to "ring" when an inbound call comes in.  If I'm understanding the docs correctly, changing to RingOut or "RingCentral App" will cause outbound calls to be launched through the app or the associated "RingOut" number.  Am I misunderstanding something?

**Comment by embbnux** [comment]
Yes, those modes will cause outbound calls to be launched out of the app. But the app can still control the call (end, transfer).

Okay, let me add a flag to handle this case. After flag enabled, developer need to handle the ringing.

**Comment by MattHoneycutt** [comment]
Awesome!

**Comment by embbnux** [comment]
In 2.x, we support to make ringtone volume to 0 to disable ringing by API:
https://ringcentral.github.io/ringcentral-embeddable/docs/integration/api/#update-ringtone-settings
