### ISSUE TITLE
Support to pause auto recording functionality

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#685]
Hello,

Is there a way that the RC Embeddable can support Pause Recording functionality as is done in the desktop app? Screenshot below:

![screenshot](https://user-images.githubusercontent.com/1136153/233465748-fb767170-3af7-41ba-97de-66ba596061ca.png)

**Comment by embbnux** [comment]
Hi @ElridgeDMello you can use this api https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#stop-record-a-call

**Comment by ElridgeDMello** [comment]
Thanks for that link. We will have to implement that as custom code in our integration, but was wondering if there is a reason that the embeddable does not provide a stop (or pause) recording button?

Also, would the [stop recording API](https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#stop-record-a-call) work if call recording is turned on for all users by default in the RC Service portal?

**Comment by embbnux** [comment]
@ElridgeDMello Yes, Stop api works for both manual recording and auto recording now

**Comment by embbnux** [comment]
Ohh, a mistake. Stop for auto recording is only support at UI button now. For API, it is not supported now. Let me add this into backlog.

**Comment by natedouds** [comment]
I'm a tad confused here. So is the widget supposed to be able to stop recording? This is something that we really need for compliance issues.

I just tested stopping recording with our widget implementation, and it does not work:
![image](https://user-images.githubusercontent.com/7424127/236012241-b82eb09f-2d19-4e33-ae07-34da3eb86d2d.png)

**Comment by embbnux** [comment]
Hi @natedouds Yes, it is supposed to be able to stop recording by Stop button for Auto recording for the widget's latest version. 
Can you check if your RingCentral account has enabled "Allow mute in auto recording" flag in Automatic Call Recording settings. https://support.ringcentral.com/mvp/admin/company-account-settings/turning-on-on-demand-automatic-call-recording.html#automatic-call-recording

**Comment by natedouds** [comment]
@embbnux - ok that solved the issue, thanks for the fast response.

Any chance we can get a more clear error message than the above? I think most people would be confused by that verbiage. Maybe something like: "Stop recording is currently not allowed for your company. Please contact your admin..." or something like that.

Basically, it would be nice for end users to know that it's not a problem with RC but it's a configuration issue.

**Comment by embbnux** [comment]
@natedouds This is a great point. Let me update it when I add the functional API for stoping auto recording.

**Comment by embbnux** [comment]
supported at v1.8.8
