### ISSUE TITLE
Inbound call ringing - no sound

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#686]
@embbnux ,

Our users (we only use Chrome browser), are reporting that after a while of using our application (which integrates with the embeddable via the adapter method), they do not hear the audio ringing on inbound calls.  The device rings, but they do not hear it.  

Is it related to [this](https://github.com/ringcentral/ringcentral-embeddable/pull/493#issuecomment-1518052705) issue/fix? And how do we use this fix in the adapter way?

**Comment by embbnux** [comment]
Hi @ElridgeDMello can you help to collect error logs about this issue?  We have a known issue from Chrome limitation.
Chrome requires user to have interaction with this widget iframe before playing audio. So if user doesn't have interaction with the widget, the ringing audio will not be played. But we need error log to confirm this known issue.

**Comment by ElridgeDMello** [comment]
Log files sent via email to dev support.

**Comment by embbnux** [comment]
Thank so much @ElridgeDMello I have got that.
