### ISSUE TITLE
SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

### ISSUE THREAD

**Issue by bear0412** [ringcentral/ringcentral-embeddable#688]
Hello.

I am working on ringcentral in IE 11 browser.
It works well in FF/Chrome, but not IE 11 browser.
When open developer console, I can see errors like bellow.

SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally.

I'd be grateful if you could share your experience with this error.
Thank you for your consideration.

**Comment by embbnux** [comment]
Hi @bear0412 this widget doesn't support IE 11 now. It is recommended to use Edge (Chromium) to replace IE.

**Comment by bear0412** [comment]
Thanks for your help.

I'd be grateful if you could tell me which version of this widget works in IE 11 browser.

Thank you.

**Comment by embbnux** [comment]
Hi @bear0412 Latest for IE 11 is v1.7.3 https://github.com/ringcentral/ringcentral-embeddable/issues/561
And IE is not full tested. Web phone (Browser call) feature is not supported at IE with browser limitation. User need to change to other calling settings.

**Comment by bear0412** [comment]
Thank you for your all help.
