### ISSUE TITLE
Disable ringcentral embedded widget dialer

### ISSUE THREAD

**Issue by huzaifa-NCRI** [ringcentral/ringcentral-embeddable#689]
how can i disable dialer in widget. so that an agent will have to click on the number on my website and call should be placed automatically to the given number. and agent cant make calls by its own but by the provided contact number

**Comment by embbnux** [comment]
Hi @huzaifa-NCRI The widget doesn't support to disable dialer only now. I add this into our backlog.
For now, you can add a style to hide or disable dialer input and call button.  https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/customize-ui-styles.md

**Comment by byrnereese** [comment]
@huzaifa-NCRI We have this on our backlog. In the meantime, Embbnux is right - you can probably achieve this with CSS or some carefully crafted Javascript. While on our internal backlog, we are going to mark this case as closed/won't fix for now.
