### ISSUE TITLE
Caller ID showing Unknown

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-embeddable#77]
When a customer calls in the caller ID shows "Unknown" but I can see what the customer name is from the event data.

![image](https://user-images.githubusercontent.com/22582720/34909921-b5ba13d4-f870-11e7-974a-8134e8688d0b.png)

![image](https://user-images.githubusercontent.com/22582720/34909923-bfb0883c-f870-11e7-9b5b-54aae79c163f.png)

**Comment by AndyHaas** [comment]
is this an issue with the data you are getting or RingCentral? I see this same issue with Googles Extension also.

**Comment by embbnux** [comment]
Yes, Chrome extension and this app uses most same codes.
this app just use local contact data from contacts API to match phone number. The name in event is provided by server. Need to find way to handle those data.

**Comment by embbnux** [comment]
From PM team, this is by design now. Currently, app only shows name when phone number is matched at contacts list.
