### ISSUE TITLE
v1.10.0 'rc-calling-settings-notify' gives empty `fromNumbers` array

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#777]
When first loading the embedded and popup in our application.
We observe that the `'rc-calling-settings-notify'` event fires twice.  
The first event has the expected number of `fromNumbers` (3 in our case), the second event has 0 `fromNumbers`:
This is what the console.log of the event.data looks like:
![Cursor_and_Welcome](https://github.com/ringcentral/ringcentral-embeddable/assets/1136153/d6771442-04ff-46d2-b91d-2529a3767090)

This is how the embedded widget looks w.r.t from numbers at this point:

![Cursor_and_Welcome](https://github.com/ringcentral/ringcentral-embeddable/assets/1136153/5722fb0b-aca4-4ba0-98ea-22465b983912)

Reloading the embedded widget in our app, shows the correct behavior in the console and embedded (only 1 event received with the correct number of fromNumbers):
![Welcome](https://github.com/ringcentral/ringcentral-embeddable/assets/1136153/73790e3d-94c4-4d9b-ab74-053fe55b93ae)

This is a regression from how this works in our current version used in Production (v1.8.7)

**Comment by embbnux** [comment]
Hi @ElridgeDMello Can you still reproduce this issue after you updated popup widget's version to v1.10.0 as you mentioned in #776

**Comment by ElridgeDMello** [comment]
@embbnux I just re-tested and it was related to the inconsistent versioning.  Sorry about that! Closing this issue.
