### ISSUE TITLE
Ability to set default ringtone via API

### ISSUE THREAD

**Issue by dani-phillips** [ringcentral/ringcentral-embeddable#814]
Please add the ability to set the default ringtone programmatically via API or config options. Right now it's a manual process for the user, we would like to have a uniform incoming call tone for all our users. 

Maybe a config option for `ringtone=url_to_ringtone.mp3` or something simple would be nice.

**Comment by embbnux** [comment]
Great point. I will add this into backlog

**Comment by embbnux** [comment]
Supported in 2.x https://ringcentral.github.io/ringcentral-embeddable/docs/integration/api/#update-ringtone-settings
