### ISSUE TITLE
VideoInternal permission

### ISSUE THREAD

**Issue by shawn1130** [ringcentral/ringcentral-embeddable#884]
I have a Next.js app which I used the iframe method to add the ringcentral embeddable. Both Video actions (Start, Schedule) is returning the same error: `RingCentral Embeddable do not have VideoInternal permission.` 

I am using the latest version of the embeddable:
`https://apps.ringcentral.com/integration/ringcentral-embeddable/latest/app.html`

My apps client id: `1ozMYd1J1Mbdpy0GY9L8vV`

My apps permission scopes:
![image](https://github.com/user-attachments/assets/e678290c-a184-4d3f-a6c8-22f7912c8c0b)

Screenshot of the error:
![4cef21e0-566b-4148-82b1-d0069ca0f655-spark-clipboard](https://github.com/user-attachments/assets/af5372db-e05b-417f-8962-02f820357680)

**Comment by embbnux** [comment]
Hi @shawn1130 Thanks for reporting this. It is a wrong appScope check issue. I will fix it soon.

**Comment by embbnux** [comment]
fixed in latest build v2.1.0
