### ISSUE TITLE
Unable to authorize code

### ISSUE THREAD

**Issue by MinhQuanGRF** [ringcentral/ringcentral-embeddable#914]
I'm processing the login, and getting the authorization code. I then authorize that code by:
```
 postMessage({
      type: 'rc-adapter-authorization-code',
      callbackUri: `http://localhost:3000/admin/ring-central-mobile?code=${code}`,
 });
```
then got error:
```
{
  "error" : "invalid_redirect_uri",
  "errors" : [ {
    "errorCode" : "OAU-109",
    "message" : "Redirect URIs do not match"
  } ],
  "error_description" : "Redirect URIs do not match"
}
```
even though the link `http://localhost:3000/admin/ring-central-mobile` has been added by me to the OAuth Redirect URI

**Comment by MinhQuanGRF** [comment]
@embbnux Could you please assist?

**Comment by embbnux** [comment]
hi @MinhQuanGRF do you pass your redirect uri to Embeddable? https://ringcentral.github.io/ringcentral-embeddable/docs/config/redirect-uri/
The code needs to be matched with redirect uri in the widget.

**Comment by MinhQuanGRF** [comment]
I have tried:
```
    postMessage({
      type: 'rc-adapter-authorization-code',
      callbackUri: `https://apps.ringcentral.com/integration/ringcentral-embeddable/latest/redirect.html?code=${code}`,
    });
```

However it also fails:
![image](https://github.com/user-attachments/assets/d95ab1d2-5e75-4e7a-b967-64edcdaf15ef)
![image](https://github.com/user-attachments/assets/ec5be14e-409f-4cc2-97d7-f919d3a38b33)
![image](https://github.com/user-attachments/assets/b7ca2e52-03c3-421b-880b-0664eb44f85b)

But if I use `rc-adapter-login`, I can still login:
![image](https://github.com/user-attachments/assets/81ccc4f6-ec62-40e5-9b4f-ea5b45fc9a85)
![image](https://github.com/user-attachments/assets/49f7e50c-4363-40a3-9916-b500b5cb2c7f)

Do you notice what problem I'm having?

**Comment by embbnux** [comment]
Hi @MinhQuanGRF can you show how you get the code? If you get the code from your own redirect URI, you need to pass your redirect uri to the widget following the document that I share in last comment

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
